### ISSUE TITLE
Embed Twitter feed on News page

### ISSUE THREAD

**Issue by hauten** [LLNL/llnl.github.io#103]
The Lab’s home page embeds a Twitter feed, but the code looks different from what I generated and according to Twitter’s documentation, which are:
•	Generated embed code for @LLNL_OpenSource: https://publish.twitter.com/?query=https%3A%2F%2Ftwitter.com%2FLLNL_OpenSource&widget=Timeline
•	Help doc: https://developer.twitter.com/en/docs/twitter-for-websites/timelines/overview

So my best guess is:
`<a class="twitter-timeline" href="https://twitter.com/LLNL_OpenSource?ref_src=twsrc%5Etfw" width="300" height="500" data-tweet-limit="2" data-chrome="noscrollbar noborders noheader nofooter transparent" data-aria-polite="assertive" data-link-color="#005dab">Tweets by LLNL_OpenSource</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`

•	It would be nice to use the left-hand sidebar area for the Twitter widget w/o sacrificing the full width of the news items. See attached image.
![possible space for twitter feed](https://user-images.githubusercontent.com/31740953/45457522-26fff300-b6a4-11e8-8f8a-135ccc8a38e4.jpg)

•	300x500 is the size of the embedded widget on LLNL’s home page. 
•	Tweet limit = 2 is also what LLNL has. We could expose more tweets since the News page is long. Maybe see what 2 looks like first?
•	Data link color appears in the LLNL widget, I believe to override Twitter’s default link color. LLNL uses #0088cc, which I switched to #005dab.

**Comment by hauten** [comment]
@IanLee1521 what do you think about adding "help wanted" and "code.gov" tags to this issue for the Dec 7-8 hackathon? Although it's not related to the portal's core functionality, it's [issue-type] enhancement [skill-level] beginner [effort] small -- per guidelines on https://github.com/GSA/code-gov/blob/master/HelpWanted.md.

**Comment by IanLee1521** [comment]
@hauten -- Good idea! Done.

**Comment by hauten** [comment]
Make sure there is a "follow us" type of call to action, whether it's the twitter icon or something else (this may be part of what's embedded). Need to think about whether we want the twitter icon somewhere on the home page.

**Comment by angfl97** [comment]
Do we still want the twitter feed to display on mobile devices?

**Comment by IanLee1521** [comment]
Maybe do whatever the feed embeded on www.llnl.gov does?

**Comment by angfl97** [comment]
pull request #180 opened to address this issue

**Comment by IanLee1521** [comment]
Resolved with #180
