### ISSUE TITLE
News idea: How to incentivize open source

### ISSUE THREAD

**Issue by IanLee1521** [LLNL/llnl.github.io#104]
We should get a blog / news post out relating to why LLNL does open source. Probably a fair bit of overlap with our S&TR article, the ASC stance, the ECP stance, etc.

cc/ @RicardoAReyes

**Comment by hauten** [comment]
@IanLee1521 Can we close this? Or need to review/discuss any further action?

**Comment by IanLee1521** [comment]
Nope, I think we can close it.
