### ISSUE TITLE
Update heading style on /news

### ISSUE THREAD

**Issue by hauten** [LLNL/llnl.github.io#111]
https://software.llnl.gov/news/

- Reduce H2 size so headlines don't look so top heavy (especially noticeable with long headline that have only a short blurb underneath) 
- Do not change H2 style on other pages, like /about
- Also fix the "nesting" problem on this page; news items should be siblings, not children, of each other

**Comment by gonsie** [comment]
@hauten would you be interested in making these changes yourself? I could show you how to get a local copy of the website on your computer so that could do development on the HTML and CSS (to see how everything would look before you commit changes).

**Comment by IanLee1521** [comment]
@gonsie -- @hauten may also need some help with her Git client too, she was having trouble getting master to update... I am not able to help until Monday, but if you are, that would be awesome.
