### ISSUE TITLE
review Oct 30 commit accidentally made to master

### ISSUE THREAD

**Issue by hauten** [LLNL/llnl.github.io#112]
https://github.com/LLNL/llnl.github.io/commit/2b0fbcdb62a35be34852f548c9116be354794d6c
Looks like I did not create a new branch before committing these changes. My apologies! No changes to existing content; just additions. @gonsie suggested I open an issue for @IanLee1521 or someone else to review this. (I will not be offended if you start making bets about when I will complete a pull request correctly start to finish.)

**Comment by IanLee1521** [comment]
I saw that and already had checked it out. No worries! :)

As an aside, I updated the repo permissions to REQUIRE a pull request now, to help guide you on the right track... :) That said, it looks like https://github.com/LLNL/llnl.github.io/pull/113 was done correctly!

**Comment by hauten** [comment]
a.k.a. Holly-proofing the repo, good idea ;)
