### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by gonsie** [LLNL/llnl.github.io#130]
We should create an RSS feed for all of our posts. I think it can be done by a simple setting in the config file, but I’m not 100% on that.

**Comment by gonsie** [comment]
An RSS feed totally exists (as of this commit: b3547a8696e2861cb445063d9e15e64141b9feb8). I guess I just didn't look hard enough!

**Comment by IanLee1521** [comment]
Does a button need to be added somewhere to make it more obvious?
