### ISSUE TITLE
Change site author 

### ISSUE THREAD

**Issue by gonsie** [LLNL/llnl.github.io#142]
The site author in the `_config.yml` file is @IanLee1521, which means that his name appears as the author on each blog post (the software news announcements). It would make more sense to use @hauten as the by line, or to have a more generic author. 

I think we can overwite that with “author:” in the yaml front matter on each post. Maybe the site author should be a generic “LC contributing staff” and each post could get its own author line.

**Comment by hauten** [comment]
My preference is for something agnostic, the team instead of a person. But the author doesn't show up anymore, right? Maybe that was the case when each post was given its own page; we have unlinked the titles.

**Comment by gonsie** [comment]
The author shows up when you read the monthly news through an RSS reader (like I do).

**Comment by IanLee1521** [comment]
The line to change is https://github.com/LLNL/llnl.github.io/blob/master/_config.yml#L2 -- I'm open to suggestions of what to make it.

Maybe `LLNL Open Source <open-source@llnl.gov>` ?

**Comment by gonsie** [comment]
That works for me. I’ll make a PR.
