### ISSUE TITLE
Put short description (paragraph) of what software.llnl.gov is at the top of the main page

### ISSUE THREAD

**Issue by neely4** [LLNL/llnl.github.io#147]
I had some comments from some folks in PLS after the RADIUSS seminar who visited software.llnl.gov. Their main comment was that it took them awhile to figure out what it was they were looking at, and a short paragraph at the top (i.e. above the "XXX Software Repositories") would be helpful to orient them.

Something like: "Welcome to the LLNL Software Portal, where all Open Source Projects hosted on GitHub are collected in one place, and updated automatically as those repositories change or new ones are added"...  (Don't use that - but you get the idea).

Other suggestions like categorizing things, sorting differently, etc... also came up as suggestions - but I think those are captured elsewhere. This one is a super easy one.

**Comment by IanLee1521** [comment]
Good suggestion. This ties in to the work that @hauten was starting to look into regarding redesigning that home page.
