### ISSUE TITLE
Showcase applications

### ISSUE THREAD

**Issue by IanLee1521** [LLNL/llnl.github.io#154]
I was talking to @richards12 who suggested that we should also consider adding categories / a way to visualize applications and proxy apps. 

Examples might include:

- Applications (tag/label as `application` ?)
    - https://github.com/LLNL/cardioid
    - https://github.com/LLNL/MacPatch

- Proxy Apps (use tag/label `proxy-application` ? -- https://github.com/search?q=topic%3Aproxy-application+org%3ALLNL&type=Repositories)
    - https://github.com/LLNL/LULESH
    - https://github.com/LLNL/MACSio
    - https://github.com/CEED/Laghos

It would be worth exploring adding an appropriate tag to bubble these up. Using the `proxy-application` and `application` labels perhaps?

Related to #17 
-------------------
Tasklist on July 2, for HOME (not radiuss):
- [x] Remove `app-infrastructure` as a category
- [x] Add new categories: `application`, `proxy-application`, `system-software`
- [x] Come up with blurbs & icons - requested icons on 7/2; blurbs:
**Applications:** Advance computing with scientific simulations and IT system management codes
**Proxy Applications:** Prepare for testing and porting applications
**System Software:** Manage clusters and parallel environments
**Complete Catalog:** Browse all LLNL open source projects
(no tags are required for Complete Catalog; it's everything)
- [x] Add to tag list: https://github.com/LLNL/llnl.github.io/blob/master/categories/README.md
- [x] Tag LLNL-org repos accordingly (see ideas in this thread)

**Comment by IanLee1521** [comment]
This will be on the new homepage, not the radiuss subpage

**Comment by tzanio** [comment]
Can I suggest also https://github.com/CEED/Laghos as a proxy app example?

**Comment by IanLee1521** [comment]
Yes please! And if you think of any others, add them. I'll update the first comment to make it easier to find the list.

**Comment by hauten** [comment]
![topic icons](https://user-images.githubusercontent.com/31740953/59952960-f919bd00-9432-11e9-80f1-11f302f53297.jpg)
How are 'applications' different from 'app-infrastructure'? Also, need to come up with ideas for icons that go with new categories. Attached are the current 6 topics.

**Comment by IanLee1521** [comment]
Hmm, good question, I guess I don't really know what `app-infrastructure` means...

Applications are meant to be fully fleshed out end products. @richards12 might have a better definition we could use.

This also makes me think that we may need some alt-text for each of the categories describing what they are...

**Comment by hauten** [comment]
Well, we do have little descriptive blurbs under each icon (I cropped them out for the screen shot above). `app infrastructure` = "Provide unified data storage and parallel logging solutions" which I came up with based on descriptions of the `app infrastructure` repos on the radiuss confluence page. Perhaps it's too narrow of a definition. (`proxy-applications` seems intuitive.) Anyway, thanks to the framework @angfl97 is putting in place, we'll be able to easily create/modify categories going forward, esp since updating topics on LLNL-org repos is painless. And I agree re: alt-text.

**Comment by richards12** [comment]
I presume app-infrastructure refers to the stuff that isn’t math and physics libraries, but that is still resuable across applications:  Stuff like Raja, Umpire, Chai, SCR, Silo, and any other “service” code.

Dave

**Comment by hauten** [comment]
> Can I suggest also https://github.com/CEED/Laghos as a proxy app example?

Yes, also whatever is open source on https://computation.llnl.gov/projects/co-design/proxy-apps

**Comment by IanLee1521** [comment]
@richards12 / @ikarlin - Do you have a good one sentence description for each of `applications` and `proxy-applications` that we can use as a blurb?

**Comment by richards12** [comment]
In addition to Laghos, you’ll want to add

https://github.com/LLNL/Quicksilver

https://github.com/LLNL/Kripke

https://github.com/LLNL/Comb

I also consider the RAJA Performance suite to be a proxy app.

https://github.com/LLNL/RAJAPerf



There may be others, but these were the ones that I found easily in a quick scan.



Dave

**Comment by richards12** [comment]
Proxy-Applications: Simplified versions of applications for testing, porting, co-design, etc.

Applications: Modeling and simulation codes for scientists and engineers

I’m not sure I’m thrilled with the blurb for applications, but based on what I *think* we’re going to put in that category, it’s the best description I can come up with on short notice. Other ideas are welcome.

**Comment by hauten** [comment]
Per today's discussion, for portal home only (not /radiuss):
1. remove `app-infrastructure` as a category
2. add new categories `applications` & `proxy-applications` - come up with blurbs & icons
3. tag LLNL-org repos accordingly (see above)

**Comment by hauten** [comment]
@IanLee1521 Do we have a file yet for the main (not radiuss) topics? The whole-portal version of https://github.com/LLNL/llnl.github.io/blob/master/radiuss/README.md

**Comment by IanLee1521** [comment]
I think we should put it here (at least for now): https://github.com/LLNL/llnl.github.io/blob/master/categories/README.md

**Comment by hauten** [comment]
@tzanio Can you please tag `proxy-application` on Laghos when you have a moment? Thanks.

**Comment by tzanio** [comment]
> @tzanio Can you please tag proxy-application on Laghos when you have a moment? Thanks.

Done

**Comment by hauten** [comment]
@angfl97 new blurb for 'applications': Advance computing with scientific simulations and IT system management codes

I updated the main comment above to reflect this

**Comment by hauten** [comment]
sorry, @angfl97 one more thing - i need to get an icon for one more category, which is everything:

**Complete Catalog:** Browse all LLNL open source projects

**Comment by angfl97** [comment]
sounds good! Just to clarify, the Complete Catalog category will show up in the main homepage beside the other categories or only in the table for the 'focused category view' page?

**Comment by hauten** [comment]
Let's put it in both places, that way we have 3x3 icons. Complete Catalog can go last in the list, though, not alphabetical order. I might change my mind once I see it, but right now it feels like it should be the last option and not get "lost" among the other categories. However, you're doing something to alphabetize them automatically (?), then don't worry about making an exception for Complete Catalog. If that makes sense.

**Comment by angfl97** [comment]
ok. yeah that makes sense

**Comment by ikarlin** [comment]
You also want to add LULESH and AMG for proxy-apps.

**Comment by hauten** [comment]
> You also want to add LULESH and AMG for proxy-apps.

They are: https://software.llnl.gov/category/#/PROXYAPPLICATIONS
They don't show up on the home page b/c that's only the first 4 repos according to stars. But they are on the overflow page. (Please keep suggesting things like this to help make tagging better!)
