### ISSUE TITLE
visit is missing from data-viz category

### ISSUE THREAD

**Issue by cyrush** [LLNL/llnl.github.io#170]
On: https://github.com/visit-dav/visit,  I think we accidentally dropped the `data-viz` tag, but I re-added it.  Is there anything else we need to do to get it to appear on software.llnl.gov under the data-viz catergory?

Thanks!

**Comment by IanLee1521** [comment]
I think we might just need to re-generate... @LRWeber / @angfl97 ?

**Comment by IanLee1521** [comment]
Ok, I'll run that now.

**Comment by IanLee1521** [comment]
And you're back!

![image](https://user-images.githubusercontent.com/828452/60474937-afe31d80-9c29-11e9-8c1b-945e729b70fc.png)

**Comment by cyrush** [comment]
hmm, seems we dropped of again?

**Comment by IanLee1521** [comment]
Hmm... @LRWeber / @angfl97 can you look into this?

**Comment by LRWeber** [comment]
It looks like the live site is still using the older data. @IanLee1521 We may need to double check that the latest master branch is fully deployed.

**Comment by IanLee1521** [comment]
Just re-deployed... Should update at the top of the hour (and sooner once I get the site moved back to GitHub Pages)

**Comment by IanLee1521** [comment]
Ok, it's back (I wonder if my screenshot was looking at the dev version...?) 

Let me know if you see any issues again!
