### ISSUE TITLE
Generate repo list for ongoing metadata cleanup

### ISSUE THREAD

**Issue by hauten** [LLNL/llnl.github.io#188]
Generate list of LLNL-org repos that includes (1) repo name, (2) description, (3) website, (4) topic tags—even if (2), (3), and/or (4) are empty.

Goal: Chip away at the "empties" over time so every repo has discoverable & meaningful metadata.

**Comment by angfl97** [comment]
Could this be a JSON file that gets generated and stored somewhere in the repository or is some other method better?

**Comment by hauten** [comment]
I am open to whatever is easiest/most convenient/best

**Comment by IanLee1521** [comment]
I vote a new Jason file alongside this era one we’re working on.
