### ISSUE TITLE
unfound repos

### ISSUE THREAD

**Issue by gonsie** [LLNL/llnl.github.io#19]
Two repos are not being found:

- [hpc/mvapich-cce](https://github.com/hpc/mvapich-cce)
- [hpc/mvapich2-cce](https://github.com/hpc/mvapich2-cce)

There are a number of repos within the HPC organization which have an LLNL person as their main contributor, including:

- [hpc/cce-mpi-mvapich2-1.9](https://github.com/hpc/cce-mpi-mvapich2-1.9)
- [hpc/mv2-2.0-cce](https://github.com/hpc/mv2-2.0-cce)
- [hpc/mpi-resilience](https://github.com/hpc/mpi-resilience) (though this is a fork of [tgamblin/mpi-resilience](https://github.com/tgamblin/mpi-resilience))
- maybe more?

**Comment by IanLee1521** [comment]
For the first 2, I suspect we can remove them without much issue, they must have been deleted at some point?

As for https://github.com/hpc/cce-mpi-mvapich2-1.9 and hpc/mv2-2.0-cce -- It looks like those are maintained by @adammoody, perhaps they would be open to moving them into the @LLNL organization?

**Comment by LRWeber** [comment]
Missing repos have been removed from the list.

Are any of these individual repos something we should add now? Additional repos can easily be added/migrated in the future.

**Comment by IanLee1521** [comment]
It might be good to add a bit into the "about" part of the site to describe how to get new repos / orgs listed. I think that's down to a trickle, but the gist is: "submit a pull request to the appropriate file", #31 was the most recent example.

For the two that don't exist, we should just remove them. (that could be it's own PR).

For the ones to move, I'll see if I can get @adammoody 's attention :)

**Comment by LRWeber** [comment]
That could be an efficient way to handle it. The appropriate file, in that case, would be:
https://github.com/LLNL/llnl.github.io/blob/master/explore/input_lists.json

**Comment by IanLee1521** [comment]
I'm guessing it should go somewhere around this section: https://github.com/LLNL/llnl.github.io/blob/master/about/using-github.md#working-with-llnl-repositories

Unless we wanted to move it to it's own (new) about page... thoughts?

**Comment by LRWeber** [comment]
Hmm... I think it would fit in on that page, though I think it should have it's own section rather than including it under "Working with LLNL Repos". That section specifically covers repos within the LLNL GitHub organization, which are already included!

**Comment by IanLee1521** [comment]
Unless it was a sub-section like: "Did we miss an LLNL repository? Fork the repository and ..."

**Comment by adammoody** [comment]
I deleted these two as well:

- hpc/cce-mpi-mvapich2-1.9
- hpc/mv2-2.0-cce

We can likely move mpiFileUtils to LLNL.  @IanLee1521, can you help us do that?

**Comment by IanLee1521** [comment]
@adammoody -- If you're an admin on the other side, you should be able to go to the settings page, and at the bottom "Transfer Ownership" to @LLNL. Since you are a member of @LLNL and therefore have create repo permission, you will be able to move it.

**Comment by IanLee1521** [comment]
@adammoody -- would you also be willing to submit a pull request updating: https://github.com/LLNL/llnl.github.io/blob/master/explore/input_lists.json

Thanks!

**Comment by IanLee1521** [comment]
@adammoody / @gonsie -- Can we get a pull request to add any repos you still feel are missing from the hpc org?

Thanks!

**Comment by adammoody** [comment]
@IanLee1521 , other than mpiFileUtils, I don't have any other repos on hpc that need to be added.

**Comment by IanLee1521** [comment]
Thanks @adammoody that looks like it's already in there: https://github.com/LLNL/llnl.github.io/blob/dfbc6d45e60fedd4e02fe626e67bc3209b31fb70/_explore/input_lists.json#L28 so I'll go ahead and close this.
