### ISSUE TITLE
Contributing / Code of Conduct

### ISSUE THREAD

**Issue by IanLee1521** [LLNL/llnl.github.io#21]
Since this repo powers the software.llnl.gov site, I think it will end up being the best thing we have as far as a "meta" repo for documentation [I've already started bits of it here](https://github.com/LLNL/llnl.github.io/tree/master/about) (which you should feel encouraged to submit pull requests to).

To that end, I would like to bring up the idea of requiring a Code of Conduct for LLNL, and additionally adding a standard CONTRIBUTING.md file to this repo which could be re-used in other projects.

I figure the CONTRIBUTING.md file is ours to right, and I would like to propose we adopt the [Contributor Covenant Code of Conduct](http://contributor-covenant.org), specifically the [markdown version](http://contributor-covenant.org/version/1/4/code_of_conduct.md).

What are the thoughts of the other @LLNL/admins ? @tzanio also has brought this up, so I'm mentioning him here too.

**Comment by davidbeckingsale** [comment]
This sounds good! I think that maybe having some templates for other documents could be helpful too.

I'm still putting together the list of steps I'm taking for updating the SAMRAI repo.

**Comment by IanLee1521** [comment]
Looking at what others have done, I'm inclined to suggest we start an "open-source-policy" repo, since to what @18F did: https://github.com/18F/open-source-policy

**Comment by davidbeckingsale** [comment]
That's a great idea, I like it.

**Comment by IanLee1521** [comment]
I just drafted up some wording and put it in a pull request (#22). I'll also look into creating an "open-source-policy" repo.

**Comment by Follett2** [comment]
FYI, the last one OSS policy that a DOE Lab did was PNNL’s  - and it took over a year, with senior official engagement over months after months of development at lower levels.  “Policy” around here has serious implications.

Charity Follett, Business Development Executive · Lawrence Livermore National Laboratory · (925) 422-1817 · follett2@llnl.gov<mailto:follett2@llnl.gov>

**Comment by davidbeckingsale** [comment]
We can always call it something else...

**Comment by IanLee1521** [comment]
Would something like "open-source-guidelines" be a better name?

**Comment by tgamblin** [comment]
Do we need to rename it?  It is unclear to me what @Follett2 wants us to do with this information.

**Comment by Follett2** [comment]
Much easier to work with.  Best practices is good – just not a policy.  And not legal language…


Charity Follett, Business Development Executive · Lawrence Livermore National Laboratory · (925) 422-1817 · follett2@llnl.gov<mailto:follett2@llnl.gov>

**Comment by IanLee1521** [comment]
I was taking the name from the common, best practices across government:

- https://github.com/cfpb/open-source-policy
- https://github.com/gsa/open-source-policy
- https://github.com/18f/open-source-policy
- https://github.com/nationalparkservice/npmap-open-source-policy
- https://github.com/US-CBP/open-source-policy
- https://github.com/USAJOBS/open-source-policy

**Comment by IanLee1521** [comment]
Great! I'll go ahead and start moving this discussion over to https://github.com/LLNL/open-source-guidelines

**Comment by tzanio** [comment]
I also like "guidelines" much more than "policy" :)

**Comment by IanLee1521** [comment]
The CONTRIBUTING bit is now at: https://github.com/LLNL/open-source-guidelines/blob/master/CONTRIBUTING.md
