### ISSUE TITLE
Empty Repositories

### ISSUE THREAD

**Issue by LRWeber** [LLNL/llnl.github.io#24]
I've come across a few repositories that, although they still exist on GitHub, are completely empty!
Specifically:
- rose-compiler/rose-sh
- rose-compiler/rose-tests-nonsmoke-functional
- zfsonlinux/zfs-linux-meta

Do we know why this is? If they are truly dead, it might be worth encouraging someone to fully delete them. They do impact certain statistics.

**Comment by Follett2** [comment]
Please don’t, unless these are really dead.  The ones listed are landing places for projects in the works that will go online pending approvals…  What statistics are they impacting?
Charity

Charity Follett, Business Development Executive · Lawrence Livermore National Laboratory · (925) 422-1817 · follett2@llnl.gov<mailto:follett2@llnl.gov>

**Comment by LRWeber** [comment]
Okay! That's fine then.

I've been collecting data about repository counts, contributing users, etc. I wouldn't want to count abandoned repositories or their associated contributors, but early WIP repos are fine.

The most notable impact was in trying to query commit history for each repo, only to find that these ones came back with completely empty responses. But it sounds like, in this case, they really don't have any history! So no need to fix that.

Thanks for the clarification!

**Comment by IanLee1521** [comment]
I think there is a compromise to be had here where we could post a README.md to hose repos with a sentence saying what that repo is and therefore why it is empty. Or even just a "Coming soon!" note would be an improvement. 

@dinatale2 is probably one of the people for ZFS

@follett2, what is the rationale for having the empty repos currently?

**Comment by justintoo** [comment]
The two empty rose-compiler repos have been removed. Thanks.

**Comment by dinatale2** [comment]
The `zfs-linux-meta` repository was removed. Thank you.
