### ISSUE TITLE
Move org / repo data to _data/

### ISSUE THREAD

**Issue by LRWeber** [LLNL/llnl.github.io#25]
Rather than having orgs / repos in `github-dynamic.js` (https://github.com/LLNL/llnl.github.io/blob/graphql-dev/js/github-dynamic.js#L7) move it into a JSON file in `_data/` (https://github.com/LLNL/llnl.github.io/tree/graphql-dev/_data)

**Comment by LRWeber** [comment]
For some reason, whenever I try to put something into _data, the webpage can't find it. However, I think I have it working in another directory.

**Comment by IanLee1521** [comment]
Is this issue solved by: https://github.com/LLNL/llnl.github.io/pull/33/files#diff-6c9d5ed8c51c667a6d0c9cbec58d79d5 ?

**Comment by LRWeber** [comment]
Yes, the new `input_lists.json` should serve as our single source.

As a relevant side note:
It is currently used by `github-dynamic.js` directly. However, once we change things so that the front page isn't sending GitHub queries, it will get the list of repos from the stored data files. The input lists would then only be used by the data-fetching scripts.
