### ISSUE TITLE
Tags on News posts

### ISSUE THREAD

**Issue by IanLee1521** [LLNL/llnl.github.io#250]
@hauten - Can we come up with a few tags for news posts to start using?

At a minimum as I look at the news posts come in, I think we have some like: `new-repo`, `new-release`, `trip-report`, etc.

For now, I'd be fine if we add them to the [Jekyll front matter](https://jekyllrb.com/docs/front-matter/) even if we don't use them on the site. e.g.

```
---
title: "New Repo: HELICS-FMI"
tags: new-repo
---
```

Maybe we can also maintain a list / table of what they mean in a README.md file in the news directory? (https://github.com/LLNL/llnl.github.io/tree/master/news)

Thoughts? Are there tags we can steal from the Comp websites all ready?

**Comment by hauten** [comment]
branch `news-filter`
