### ISSUE TITLE
Filter news by tags

### ISSUE THREAD

**Issue by hauten** [LLNL/llnl.github.io#252]
Filter the News & Archive pages by tag that's compatible with the year rollup in issue #194. Filtered results should remain in reverse chronological order. See issue #250 for background. List of tags is in News > README. Another site with similar feature: https://pls.llnl.gov/research-and-development/nuclear-and-chemical-sciences/resources

**Comment by hauten** [comment]
branch `news-filter`

**Comment by hauten** [comment]
https://github.com/cagrimmett/jekyll-tools#filtering-categories-with-isotope
http://code.parts/2015/12/11/filter-posts-by-tag-in-jekyll/

**Comment by hauten** [comment]
- [ ] remove commas from tags on newer posts
- [ ] create tag collections so each tag can be clickable
- [ ] user can go back to All (unfiltered
- [ ] style the clickable tag

**Comment by hauten** [comment]
@aidan-epperly I could not figure out how to do this. I ended up creating a new page for Events under News, which filters to show posts with `event` or `event-report` tags. If you can figure out how to filter all the news by any tag, then we probably don't need the Events page. As for News vs Archive, the former shows only the 20 latest posts. So we'd probably want both of those pages to have the tag filters. Other ideas are welcome.

**Comment by aidan-epperly** [comment]
Hmm, alright. I am not really even sure how the news site works, so I am not sure what I can do, but I will give it a try.

**Comment by aidan-epperly** [comment]
I think that I have figured out how the other site did it, so I may be able to implement it.

**Comment by aidan-epperly** [comment]
Good first step, got the articles to have classes based on tags:
![image](https://user-images.githubusercontent.com/29114346/91614595-b3119080-e936-11ea-8f6b-34e6cdae28af.png)
