### ISSUE TITLE
New repo category: file-systems

### ISSUE THREAD

**Issue by hauten** [LLNL/llnl.github.io#258]
Several repos are already tagged with this topic. Implement the new category on the main catalog only.
- [x] Ask designer for new icon
- [x] Add description and tag to https://github.com/LLNL/llnl.github.io/blob/master/category/README.md
- [x] Add category to main catalog browse (/category/#/FILESYSTEMS, category_info.json)
- [x] Make sure mobile break points are still OK
- [x] Document the steps to add a new category

**Comment by hauten** [comment]
branch `file-systems-category`

**Comment by hauten** [comment]
All tasks done. However, the image is not the right size. The replacement svg isn't either. Neither have the same type or amount of metadata as the other icons. Not sure how to solve this but will continue investigating.

**Comment by IanLee1521** [comment]
I wonder if @LRWeber might have some ideas about the SVG file?

**Comment by LRWeber** [comment]
Added a new commit to the branch, the SVG should at least look right now.
