### ISSUE TITLE
Numbered list items all #1 in Jekyll rendering

### ISSUE THREAD

**Issue by IanLee1521** [LLNL/llnl.github.io#26]
The actual page https://software.llnl.gov/about/using-github/ renders the numbered list as all `1.` items, when the Markdown in the repo here does not.

This is likely an issue with the Markdown renderer that we're using on the site (kramdown currently?), but we should figure out what's going on there, and may need to change to a different one (whatever GitHub is using..?)

**Comment by gonsie** [comment]
Yes, this is a quirk within Kramdown (the only supported parser for jekyll & GitHub pages). Adding an extra indent before the sub-bullets fixes the rendering (and makes the rendering identical between GitHub-flavored-md and kramdown).
