### ISSUE TITLE
New Lab website theme

### ISSUE THREAD

**Issue by hauten** [LLNL/llnl.github.io#283]
See llnl.gov, which switched in early October to a new look & feel. Many other Lab sites have been updated as well. To what extent can we conform, and how would we do it?
![LLNL header](https://user-images.githubusercontent.com/31740953/66519348-fdc6b780-ea9b-11e9-960b-bc8295ff0854.JPG)
![LLNL footer](https://user-images.githubusercontent.com/31740953/66519353-01f2d500-ea9c-11e9-85ef-7a0859605614.JPG)

**Comment by hauten** [comment]
There is also a "skinny footer" version, which I like better for the portal: https://data-science.llnl.gov/. Comp web team (Justin M) has the code.

**Comment by IanLee1521** [comment]
We would need to update our base theme (https://github.com/LLNL/Jekyll-LLNL-Theme/) to use that new code (css, html layout, etc).

This is mildly amusing to me since I'd been trying to get that upstream style for years and want to update a couple of places with it (we have some internal repos that could / should be updated).

**Comment by hauten** [comment]
Is this something @aidan-epperly can do? Not to co-opt his internship or priorities, but this is outside my skill set. We would need to suppress the search box; the portal isn't indexed like a regular site.

**Comment by IanLee1521** [comment]
I'm asking @justinmello32 if he can do it first, since I think he did / is doing the Drupal version of this.

**Comment by aidan-epperly** [comment]
It's not something that I know how to do currently, but it is something that I would be interested in learning.

**Comment by IanLee1521** [comment]
We're working on getting @justinmello32 in to Slack so he can chat with you, but he's game to work with you on this

**Comment by justinmello32** [comment]
Just following up on this so we have it here but I'll checkin with @aidan-epperly when I have some time.

**Comment by hauten** [comment]
This is happening with the FY23 redesign. We will have our own instance of the Lab theme, which means we'll have to keep it updated when things change at the Lab level.
