### ISSUE TITLE
Site accessibility compliance: headings

### ISSUE THREAD

**Issue by hauten** [LLNL/llnl.github.io#286]
Evaluate these issues and fix where appropriate:
- [x] No headings on page
- [x] No top-level heading on page
- [x] Structure headings

**Comment by hauten** [comment]
@IanLee1521 Is the intent with the license text files (such as https://software.llnl.gov/about/licenses/#3-open-source-license-file) to be copied/saved as-is by someone creating a repo? The accessibility checker is flagging them as problematic because they don't have a heading that a screen reader (for a visually impaired person) can use for context. I can mark them to be ignored by the accessibility checker if they are OK as is -- versus some other solution like turning them into .md files.

**Comment by IanLee1521** [comment]
Yes, they are intended to be the verbatim text that folks can copy and paste. I would say ignoring them is the way to go.

**Comment by hauten** [comment]
In that case, there's nothing to change
