### ISSUE TITLE
Use cdn.llnl.gov instead of static assets

### ISSUE THREAD

**Issue by IanLee1521** [LLNL/llnl.github.io#34]
Instead of using the static assets bundled in this site, we should use the cdn.llnl.gov resource instead.

**Comment by LRWeber** [comment]
Is this in reference to the D3 extensions? That part has already been updated (though I still need to update the README to reflect all the latest changes).
https://github.com/LLNL/llnl.github.io/commit/e50f02073fcec8ee843f6be75b36f3c090aa40f0#diff-3c5689c9d47638c3af459d7ac1f26dc5

**Comment by IanLee1521** [comment]
There are a few other places as well: https://github.com/LLNL/llnl.github.io/blob/0216a5d4a3b6914d5ac01f32e7d1d33bff88efb0/_includes/head.html#L8

**Comment by LRWeber** [comment]
I've tried resolving this issue, but when I preview the site, it looks like many of the icons are missing (I believe these come from font-awesome).
I'm not sure if this is a bug that needs to be resolved, or if it will resolve itself on the live site. (It might, because the "Fork me" banner is similarly missing in my preview, but fully functional on the live site.) 

Is there a way to check this?
https://github.com/LLNL/llnl.github.io/tree/staticmigration

**Comment by IanLee1521** [comment]
For me I see font-awesome coming from cdn.llnl.gov... You might need to try removing your built site in your filesystem (`rm -r _site`), clearing your caches, and trying to view it again?

**Comment by LRWeber** [comment]
The icons are currently missing on the live site

**Comment by IanLee1521** [comment]
Can you show a screenshot? They appear for me. You might need to try clearing your browser cache as well, if it is holding on to the old URLs.

**Comment by LRWeber** [comment]
I've cleared the cache and tried it in multiple browsers. They all look something like this.
![missingicons](https://user-images.githubusercontent.com/29315109/29787374-8657db7a-8be3-11e7-99f1-1730a25d4d04.png)

**Comment by gonsie** [comment]
Those icons are from the font-awesome package. This issue may be hard to debug it you have font-awesome installed on your local machine (which I'm guessing that Ian does, I know I do).

**Comment by IanLee1521** [comment]
What is strange is that for me, I see font-awesome being served by cdn.llnl.gov in the network monitoring of my browser: 

![screen shot 2017-08-28 at 12 07 04](https://user-images.githubusercontent.com/828452/29789013-828f49be-8be9-11e7-850f-954e1d4a055f.png)

**Comment by LRWeber** [comment]
I do see some errors on the console that are probably related.

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cdn.llnl.gov/font-awesome/4.4.0/fonts/fontawesome-webfont.woff2?v=4.4.0. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).  (unknown)`

`downloadable font: download failed (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:1): bad URI or cross-site access not allowed source: https://cdn.llnl.gov/font-awesome/4.4.0/fonts/fontawesome-webfont.woff2?v=4.4.0`

**Comment by IanLee1521** [comment]
Interesting... I was able to reproduce that for me on Chrome and Firefox. I wasn't seeing it in Safari though. Maybe we will need to move this back to hosted on software.llnl.gov instead of cdn.llnl.gov, at least temporarily..

**Comment by LRWeber** [comment]
This may help to resolve the issue:
https://www.w3.org/wiki/CORS_Enabled#How_can_I_participate.3F
My guess is that we would just need to add the header to allow https://cdn.llnl.gov

**Comment by LRWeber** [comment]
Actually it may be the reverse: that https://cdn.llnl.gov/ needs the additional header to allow http://software.llnl.gov/ (or perhaps more, given that the point of hosting assets there is to allow them to be loaded elsewhere?).

> Granting JavaScript clients basic access to your resources simply requires adding one HTTP Response Header, namely:
> 
>  `Access-Control-Allow-Origin: *`
>  `Access-Control-Allow-Origin: http://example.com:8080`
> 
> The asterisk wild-card permits scripts hosted on any site to load your resources; listing a specific <base URI> will permit scripts hosted on the specified site -- and no others -- to load your resources.
> 
> This is compatible with both XHR XMLHttpRequest and XDR XDomainRequest, and is supported by all the major Web browsers.
> 
> (Note that it is not possible to grant access to multiple specific sites, nor use a partial wildcard match. It is also not possible to specify more than one Access-Control-Allow-Origin header.)

**Comment by IanLee1521** [comment]
Correct, looks like it needs to be on the cdn.llnl.gov server side. I have a request in to that webmaster to update. Stay tuned!

**Comment by LRWeber** [comment]
I'm getting all of the icons on my local desktop now. When I check my phone browser, however, they are still missing. So I'm not sure if the problem is actually fixed except for mobile, or if some recent updates I did included font-awesome....

**Comment by LRWeber** [comment]
Update: My phone browser shows the Font Awesome icons just fine recently, so I think the existing library issues are resolved.

Was this primarily to avoid packaging these libraries into the site itself? Or do we want all external libraries to come from cdn.llnl.gov? It looks like we're still pulling the angularjs library from googleapis. Would we want to host that ourselves too?

**Comment by LRWeber** [comment]
@IanLee1521 Can we consider this issue resolved at this point?

**Comment by LRWeber** [comment]
Actually, we have a few external references:
- Angular JS
- Twitter
- GitHub (for the "fork me" corner ribbon)
- D3 simple slider

**Comment by IanLee1521** [comment]
Honeslty I've gone back and forth about this as a whole... Do you have thoughts about our using our own cdn vs external cdns? I think I cared more in the past than I might now...

**Comment by IanLee1521** [comment]
I'm open to suggestions

**Comment by LRWeber** [comment]
I think having our own CDN mostly helps us control the reliability of those libraries; We know they won't just disappear, and if it goes down, it is something actionable on our side.

We're down to just the GitHub and Twitter bits being external, but I think those make sense to keep that way. They rely on those external services being up and running to provide functionality, whereas the libraries used to render our content can be fully self contained.

**Comment by IanLee1521** [comment]
Sounds good to me. I'll close for now and we can always re-open if we need.
