### ISSUE TITLE
Add Zoomable Graph to Explore Page

### ISSUE THREAD

**Issue by aidan-epperly** [LLNL/llnl.github.io#358]
I am currently working to add a zoomable graph to the [explore page](https://software.llnl.gov/explore/) following the [d3-pack structure](https://observablehq.com/@d3/zoomable-circle-packing). The information will be organized:
* LLNL
  * Individually tracked repos
  * GitHub Orgs
    * Repos
      * Contributers

**Comment by aidan-epperly** [comment]
First pack graph of data:
![image](https://user-images.githubusercontent.com/29114346/86662232-60a09d00-bfa1-11ea-80f3-60413b66410d.png)

**Comment by aidan-epperly** [comment]
Close Up of Recolored Pack Graph:
![image](https://user-images.githubusercontent.com/29114346/86664109-3f40b080-bfa3-11ea-922d-aff95ec7ce82.png)

**Comment by IanLee1521** [comment]
Very cool!

What are do the sizes of the circles represent? Is that going to be configurable (e.g. a slider like the license visualization)?

**Comment by aidan-epperly** [comment]
Currently the size of the smallest circles is just "1" representing one person. The circles above them are sized to hold the circles below.

**Comment by aidan-epperly** [comment]
Here is a picture of the spack bubble post zoom animation:
![image](https://user-images.githubusercontent.com/29114346/86944825-251ae580-c0fd-11ea-9d98-d04ba677374a.png)

**Comment by aidan-epperly** [comment]
And here is a picture of the whole graph borderless:
![image](https://user-images.githubusercontent.com/29114346/86945383-cace5480-c0fd-11ea-9060-7e690e2a2b88.png)

**Comment by aidan-epperly** [comment]
Raja contributors:
![image](https://user-images.githubusercontent.com/29114346/86978475-dfc5da80-c133-11ea-867d-d6ba200f6d6e.png)

**Comment by IanLee1521** [comment]
Awesome. I like the borderless images.

It looks like these are the "mentionable users" ? is that true? I still think we might need to flip this to the true "contributors"

**Comment by LRWeber** [comment]
> It looks like these are the "mentionable users" ? is that true? I still think we might need to flip this to the true "contributors"

I don't think we've ever found a way to make that distinction based on the data the GitHub API can provide.

**Comment by aidan-epperly** [comment]
Current labels:
![image](https://user-images.githubusercontent.com/29114346/87178843-ab1c6500-c292-11ea-9ce7-9a15b12e155b.png)
![image](https://user-images.githubusercontent.com/29114346/87178880-b8d1ea80-c292-11ea-99ef-b20837dbe710.png)
![image](https://user-images.githubusercontent.com/29114346/87178937-c9826080-c292-11ea-959e-98b1690cf339.png)

**Comment by aidan-epperly** [comment]
> It looks like these are the "mentionable users" ? is that true? I still think we might need to flip this to the true "contributors"

@IanLee1521 

As @LRWeber said, at least as of May 29 of this year, you still cannot use Github's v4 API to pull true contributors per [this thread](https://github.community/t/graphql-get-repository-contributors/14422/5).

**Comment by IanLee1521** [comment]
Bleh... good to know and have a reference... I wonder if I can ask around a bit...

**Comment by aidan-epperly** [comment]
Adaptive text fit:
![image](https://user-images.githubusercontent.com/29114346/87206719-47f4f780-c2bf-11ea-9838-b1e510eabee8.png)
![image](https://user-images.githubusercontent.com/29114346/87206740-55aa7d00-c2bf-11ea-90bf-9ac047d36a18.png)

**Comment by IanLee1521** [comment]
I like the adaptive text sizing
