### ISSUE TITLE
Update instructions for adding/removing repos from LLNL org

### ISSUE THREAD

**Issue by hauten** [LLNL/llnl.github.io#360]
https://software.llnl.gov/about/using-github/#working-with-llnl-repositories
Inspired by issue #355 (see comments therein), this section needs an update for the scenario in which a repo moves to another org and/or is replaced by a new repo. Might be worth making this section its own page, as the whole Using GH page is getting long.

**Comment by IanLee1521** [comment]
It might also be worth combining in this content https://software.llnl.gov/about/contributing/ which I think is similar...

**Comment by IanLee1521** [comment]
There are definitely some help topics that I get somewhat regularly that it would help us to have better documented.

**Comment by hauten** [comment]
@LLNL/github-core Does anyone have strong feelings one way or the other about these ideas?

**OPTION 1, pages under About divided by type of user/reader**
- For Employees (Account Setup, LLNL Org, Repo Mgmt)
- For Contributors
(move Other Resources onto the About page)

**OPTION 2, pages under About divided by topic**
- Account Setup
- LLNL Org
- Repo Mgmt
- Contributing
- Resources (either standalone added to About page)

Also, should we set up redirects if any of the About pages get renamed? (I like "Repo Management" the more I think about it.) I don't know how redirects work (i.e., who does it) with a site like this (vs. a "regular" Lab site).

**Comment by hauten** [comment]
> There are definitely some help topics that I get somewhat regularly that it would help us to have better documented.

Another idea would be to turn everything in FAQ:

- How do I set up my GH account?
- How do I join the LLNL org?
- How do I contribute to an LLNL repo?
- I just got my code reviewed and released, now what?
- Etc.

**Comment by LRWeber** [comment]
The FAQ version sounds like a good idea. It minimizes the need for users to search through multiple pages to find the answer they need.

If we take that approach we may want a "table of contents" type list at the top with the various questions that link to the full question-and-answer further down the page.

**Comment by IanLee1521** [comment]
I like that FAQ idea a lot.

And Jekyll can generate a table of contents with those deep links automatically...  I did that on our internal dev site, and it worked well.
