### ISSUE TITLE
Add Functionality to Activity Line Graph

### ISSUE THREAD

**Issue by aidan-epperly** [LLNL/llnl.github.io#361]
Ian said that it might be interesting to add a mousover event to the activity line graph that brings up a sunburst diagram breaking down the commits for a week by repo or organization. It would also be interesting to add a mouseclick event to the points that takes you to the events that took place that week in the news archive.

**Comment by aidan-epperly** [comment]
My current plan for this is to add a click event to the circles on the line graph that would cause the x-axis to shrink thus allowing for a pie chart breakdown of that week's activity on the side. There is another option that I thought of that would add a mouseover event that creates a pie chart around a specific point with the same information, but I don't think that would be as useful.

**Comment by aidan-epperly** [comment]
Small line graph:
![image](https://user-images.githubusercontent.com/29114346/88316017-fdff0f00-cccb-11ea-973d-39c9d0b1ab3e.png)

**Comment by aidan-epperly** [comment]
Pie chart:
![image](https://user-images.githubusercontent.com/29114346/88344537-a62acd00-ccf8-11ea-9a92-035b2dbb661d.png)

**Comment by aidan-epperly** [comment]
Dynamic Labels:
![image](https://user-images.githubusercontent.com/29114346/88345944-fc4d3f80-ccfb-11ea-96dd-926833b8a7f5.png)

**Comment by IanLee1521** [comment]
That is really slick looking I like that a lot.

v2 with the dynamic labels seems better to me. I think the pie chart to the side is best. Do you have to click to update the chart, or is it done via mouse over?

**Comment by aidan-epperly** [comment]
PR #389 solves this.

**Comment by LRWeber** [comment]
I do have one suggestion:
It might be a good idea to note which week the displayed Commit Breakdown is referring to, like the "Week of 2020-07-13" labels in the tooltips.
Otherwise, there's no indication at all as to which week you might have clicked on.
