### ISSUE TITLE
New pages under explore

### ISSUE THREAD

**Issue by aidan-epperly** [LLNL/llnl.github.io#366]
#365 is indicative of the problem that we are going to have with the size of the new graphics. Ian had mentioned making more pages under the explore umbrella in order to deal with this sort of issue.

**Comment by aidan-epperly** [comment]
#388

**Comment by IanLee1521** [comment]
Does #388 mean we can now close this one?

**Comment by aidan-epperly** [comment]
I meant to make a better comment, but I was distracted and didn't want to forget to mention the PR. I think the question is, do we want to move anything else to other pages or make any other topic specific subpages like we had talked about in the past. I know we had talked about a "What's New" and "What's Hot" page.

**Comment by aidan-epperly** [comment]
If not, then we can close this.

**Comment by IanLee1521** [comment]
Nod. I don't have any specific thoughts on things to go to a different page. I just know I've seen a bit more time loading the pages with the new graphics, and wonder how we might over come that (breaking to multiple pages was just the first thought I had).

I'll close this for now, but let's plan on thinking about how we can move things around going forward if we think that would yield better performance / UX.

**Comment by aidan-epperly** [comment]
> I just know I've seen a bit more time loading the pages with the new graphics, and wonder how we might over come that (breaking to multiple pages was just the first thought I had).

Yes, I have definitely noticed this too. Moving the dependency stuff to its own page really helped it's performance as well and made the license sunburst a little faster too.
