### ISSUE TITLE
Add to licenses sunburst

### ISSUE THREAD

**Issue by IanLee1521** [LLNL/llnl.github.io#367]
Please to the license sunburst where license is:

- [x] Other -- #371
- [ ] Unknown (to GitHub)

**Comment by IanLee1521** [comment]
Actually, apparently I was over eager... #371 only solves the "other" part, not the "Unknown" part

**Comment by aidan-epperly** [comment]
From what I have been able to tell, without doing some sort of license identification, there is no way to differentiate between whether the repo is licensed properly and just not detected by github and whether the repo is licensed under a non-tracked license. If we don't want to try to do something like that ourselves, we should probably close this issue. One example of a repo who's license issues I have not been able to diagnose is [LLNL/wcs](https://github.com/LLNL/wcs/issues/20). As documented in the link, I tried many different options for fixing the license file, and it still did not work. I think the fault may not lie within us, but in licensee/licensee.
