### ISSUE TITLE
Add repo dependency graph

### ISSUE THREAD

**Issue by IanLee1521** [LLNL/llnl.github.io#368]
It would be interesting to explore adding a dependency graph of repos, perhaps using the [GitHub Dependency Graph functionality](https://docs.github.com/en/github/visualizing-repository-data-with-graphs/about-the-dependency-graph) (now has more languages).

Scraper dependencies: https://github.com/LLNL/scraper/network/dependencies

**Comment by aidan-epperly** [comment]
> This part of the schema is currently available for developers to preview. During this preview period, the API may change without any advance notice. Please see the [Access to a Repositories Dependency Graph preview](https://developer.github.com/v4/previews/#access-to-a-repositories-dependency-graph) for more details.
>
> Note: The GraphQL resources under preview cannot be accessed via the Explorer at this time.

This is from the GitHub API v4 [page for the dependency graph](https://developer.github.com/v4/object/dependencygraphmanifest/). The long and short of it is that viewing the dependency graph through the api is a new feature, and the way that it works may change. We can, however, still use it.

**Comment by aidan-epperly** [comment]
Update: The scraper tool currently does not allow for the addition of headers to queries. However, in order to use the query for dependencies, we would need to add a custom header.

**Comment by LRWeber** [comment]
> Update: The scraper tool currently does not allow for the addition of headers to queries. However, in order to use the query for dependencies, we would need to add a custom header.

A new PR is underway that should make that possible. https://github.com/LLNL/scraper/pull/54
However, we may want to address the Travis check errors. They appear to be the result of a new flake8 update rather than any actual code changes.

**Comment by aidan-epperly** [comment]
It is my understanding that the PR has been merged and I can now use the header, is that correct @LRWeber?

**Comment by LRWeber** [comment]
> It is my understanding that the PR has been merged and I can now use the header, is that correct @LRWeber?

Yes, but not quite fully.

If you clone the repo and use the local copy of the library in your Python environment, then yes, you can start testing with it.

However, to be able to utilize this in production, it also needs a formal release to make it available to `pip install` when the scripts run.

**Comment by IanLee1521** [comment]
Just published! https://pypi.org/project/llnl-scraper/0.9.0/

**Comment by aidan-epperly** [comment]
Example of current data:
![image](https://user-images.githubusercontent.com/29114346/87458072-40cf3180-c5be-11ea-94ac-8ff30e7db57d.png)

**Comment by IanLee1521** [comment]
Yeah, so a thought would be to maybe separate the graphs by `packageManager` then ?

**Comment by aidan-epperly** [comment]
Yeah, that would be good. Here is the first of the graphs:
![image](https://user-images.githubusercontent.com/29114346/87465330-4d0cbc00-c5c9-11ea-83f4-08a6e8726291.png)

**Comment by aidan-epperly** [comment]
![image](https://user-images.githubusercontent.com/29114346/87466031-70843680-c5ca-11ea-88d4-23c9eba21ea3.png)
Green are both llnl repos and packages

**Comment by IanLee1521** [comment]
Shiny... I don't think I have any idea what that's doing from the static image... but it's cool!

**Comment by aidan-epperly** [comment]
This is the graph when it is filtered to remove all repos without dependents. Red are external packages, green are internal packages, blue is internal repos:
![image](https://user-images.githubusercontent.com/29114346/87474656-4afe2980-c5d8-11ea-9e0d-91a3270cf133.png)

**Comment by aidan-epperly** [comment]
![image](https://user-images.githubusercontent.com/29114346/87477994-e776fa80-c5dd-11ea-9a7d-9c1d96573073.png)

**Comment by aidan-epperly** [comment]
![image](https://user-images.githubusercontent.com/29114346/87482084-8e12c980-c5e5-11ea-9a48-7d15b175764d.png)

**Comment by IanLee1521** [comment]
I like that with the legend.

Is there any sort of zoom / mouse over? Or is that a second pass sort of thing?

**Comment by aidan-epperly** [comment]
So, right now, all of the nodes and links have titles similar to the sunburst and zoomable. So, if you wanted to know which two nodes, for instance, you could mouse over a link, though it takes a little finesse. There is no zoom right now because this data is actually all of the repos we have that have dependencies. I can do a zoom of some kind, but it will take a bit of work to make it work.

**Comment by aidan-epperly** [comment]
I implemented a BFS algorithm to show only the nodes that are some depth away from any node you mouseover. This is LLNL/hatchet depth 2:
![Screenshot (25)](https://user-images.githubusercontent.com/29114346/87486179-92dc7b00-c5ef-11ea-9470-98d01909670e.png)

**Comment by aidan-epperly** [comment]
New and improved. Centered on LLNL/scraper (title doesn't appear in screenshots):
![Screenshot (27)](https://user-images.githubusercontent.com/29114346/87486790-eb604800-c5f0-11ea-8998-9f0db630fa11.png)

**Comment by aidan-epperly** [comment]
Ghost lines:
![Screenshot (29)](https://user-images.githubusercontent.com/29114346/87487175-cddfae00-c5f1-11ea-88e1-9ff614ef75b7.png)

**Comment by IanLee1521** [comment]
I agree, I'm liking the ghost lines

**Comment by LRWeber** [comment]
I like the looks of the new mouseover functionality! It helps to surface more information.
And the ghost lines is definitely better than hiding the rest.

Would it be possible to do an opacity change based on the BFS depth? The binary option of highlighted vs ghosted makes the highlighted clusters still feel more disconnected, which is a bit misleading.... It's also unclear to a random user what the criteria is for what gets highlighted.

**Comment by aidan-epperly** [comment]
> Would it be possible to do an opacity change based on the BFS depth? The binary option of highlighted vs ghosted makes the highlighted clusters still feel more disconnected, which is a bit misleading.... It's also unclear to a random user what the criteria is for what gets highlighted.

Yes, I can see that. Right now, there actually isn't a way to do that with the current implementation, but I can rewrite the BFS code to add that. Right now, it computes depth 1 bfs on a set of nodes iteratively. I will have to actually implement node/line removal to keep track of depth.

**Comment by LRWeber** [comment]
> Yes, I can see that. There actually isn't a way to do that with the current implementation, but I can rewrite the BFS code to add that. Right now, it computes depth 1 bfs on a set of nodes iteratively. I will have to actually implement node/line removal to keep track of depth.

Okay, we could put that as a to-be-added feature. I think it would still be worth getting the current version up in the meantime!

My one other concern prior to making it live is the color scheme; The dark, muted red and green don't quite mesh with the rest of the page (plus the issue of red-green color-blind-ness!).
How would it look to use our dark-blue and light-blue (e.g. on Members graph) in place of the dark green and light green, and maybe the green (e.g. on Creation History graph) to replace the red?

**Comment by aidan-epperly** [comment]
> I'm not sure how deep our connections go; we probably want to adjust the cutoff accordingly.

The furthest two nodes in any connected component are is 11.

**Comment by LRWeber** [comment]
Added via #377

**Comment by aidan-epperly** [comment]
Things to do:
--------------
- [ ] Add filtering by Org, Keyword, package manager, etc.
- [ ] Remove duplicated links in graph
- [ ] Add on click event to nodes
- [ ] Make mouseover easier on links
- [ ] Org level dependencies

**Comment by aidan-epperly** [comment]
@IanLee1521 I am wondering what you think about the graph as it stands right now? This is basically the graph that I was thinking that we couldn't implement. Do you still want me to work on implementing the different types of simpler graphs that we had talked about? I have been trying to implement one such graph, but my approach didn't pay off so I was going to give it a rest until tomorrow.

**Comment by aidan-epperly** [comment]
Dependency graph simplified:
![image](https://user-images.githubusercontent.com/29114346/87704006-8885c280-c750-11ea-93c7-b29630ae0630.png)

**Comment by aidan-epperly** [comment]
Nodes are linked if they are both connected to the same package

**Comment by aidan-epperly** [comment]
Organization level view:
![image](https://user-images.githubusercontent.com/29114346/87828311-7fb8ed80-c831-11ea-9ddd-3dade510b4df.png)
It is in real need of filtering, but to do that, I will need to write a new query and scraper code.

**Comment by aidan-epperly** [comment]
![image](https://user-images.githubusercontent.com/29114346/87837414-4770d980-c848-11ea-9330-28b4ef67bf7a.png)

**Comment by aidan-epperly** [comment]
Same coarsening as before, but on the org level

**Comment by aidan-epperly** [comment]
After a long time debugging I got the filter working to show only verified package owners:
![image](https://user-images.githubusercontent.com/29114346/87997543-3fb06f80-caaa-11ea-8cdf-4c5d3b41b6e5.png)

**Comment by IanLee1521** [comment]
Very cool, I'm liking this.

I think the next big thing is I think we need to split it out to it's own page (`/exlore/dependencies/` or something) and give it a bigger (wider, taller) canvas to visualize on.

**Comment by aidan-epperly** [comment]
Bigger Visualization:
![image](https://user-images.githubusercontent.com/29114346/88103179-83ac7e80-cb55-11ea-803f-d6a2f9f0933f.png)
![image](https://user-images.githubusercontent.com/29114346/88103208-8dce7d00-cb55-11ea-8948-50b33f7ff9b4.png)
![image](https://user-images.githubusercontent.com/29114346/88103259-9d4dc600-cb55-11ea-902d-3a0ccb09136d.png)
![image](https://user-images.githubusercontent.com/29114346/88103301-aa6ab500-cb55-11ea-8c7a-785655f09226.png)

**Comment by aidan-epperly** [comment]
Also, what do people think of the org level view with/without unverified orgs? I like the view with unverified orgs better, but there are a lot that are just the names of people, and that is a little bit problematic I think.

**Comment by LRWeber** [comment]
> I like the view with unverified orgs better, but there are a lot that are just the names of people, and that is a little bit problematic I think.

I agree, limiting it to verified only strips away a lot.

Couldn't we get just the orgs instead of people? I believe we have 3 identifiable states:

- `"isVerified": false`
- `"isVerified": true`
- no "`isVerified`" property at all

**Comment by aidan-epperly** [comment]
> We would just need to filter out any that are missing that "isVerified" property.

Yes! That would be much better. I can finally use a "===" in a practical setting.

**Comment by aidan-epperly** [comment]
Also, new click event generates labeled tree:
![image](https://user-images.githubusercontent.com/29114346/88109356-33d2b500-cb5f-11ea-8aa7-a1541e4f9a13.png)

I plan to put some context and labeling.

**Comment by aidan-epperly** [comment]
Also plan to highlight and possibly number the nodes that are in the tree in the graph.

**Comment by aidan-epperly** [comment]
All verified organizations LLNL depends on:
![image](https://user-images.githubusercontent.com/29114346/88110528-36360e80-cb61-11ea-8a30-ed05f53a0e29.png)

**Comment by aidan-epperly** [comment]
All organizations LLNL depends on:
![image](https://user-images.githubusercontent.com/29114346/88112003-d856f600-cb63-11ea-8aed-d03826314c5a.png)

**Comment by LRWeber** [comment]
Would it be possible to also sort those lists alphabetically?

**Comment by aidan-epperly** [comment]
Alphabetical:
![image](https://user-images.githubusercontent.com/29114346/88113951-b52e4580-cb67-11ea-9d62-5f3aecf4aabc.png)

**Comment by aidan-epperly** [comment]
Current appearance:
![image](https://user-images.githubusercontent.com/29114346/88212883-d006c580-cc0c-11ea-9cd7-df901f146919.png)
 Hovering over a point in the tree runs a bfs shading that highlights the point and it's neighbors, clicking on a point in the tree generates a new tree centered at that point.

**Comment by aidan-epperly** [comment]
Centering:
![image](https://user-images.githubusercontent.com/29114346/88214691-6e942600-cc0f-11ea-8350-18faa1c3d66a.png)

**Comment by aidan-epperly** [comment]
Text Resizing:
![image](https://user-images.githubusercontent.com/29114346/88216923-a2bd1600-cc12-11ea-9705-a91de4bdd06f.png)
