### ISSUE TITLE
Revise dependency graph, sunburst, pack, and activity changes.

### ISSUE THREAD

**Issue by aidan-epperly** [LLNL/llnl.github.io#394]
This issue will serve as a general list of revisions that need to be made to the visualizations that I have made this summer. My plan as of now is to go back and add tooltips where appropriate instead of built in titles (#389), and to go back and add a legend to the pack diagram. If anyone (@LRWeber @IanLee1521 ) has any ideas for things to change, please let me know.

**Comment by aidan-epperly** [comment]
PR #396 adds tooltips for the graph, sunburst, and activity pie.

**Comment by aidan-epperly** [comment]
PR #398 wraps up the need for tooltips in the visualizations. One thing that I haven't "fixed" is how clicking through works with the diagram. Right now, you cannot click on individual users, and that can make it somewhat difficult to click down from the highest level view straight down to the repo level. I don't find this to be a problem, because it is still easy to go from LLNL -> Org -> Repo.

**Comment by LRWeber** [comment]
Observations copied from #398 discussion:

> It looks like the tips don't work on or through text, i.e. if you hover directly over a name instead of the circle around it, or if you try to hover over something behind the upper level's text.
> 
> It is also slightly awkward to have the tips for the lowest levels active in the upper levels; I could be trying to hover over the `hpcgroup` just to read the group name, but instead I keep seeing repo and user names unless I'm carefully aiming for the outer edge (which most people are unlikely to do).
> 
> Something else we might want to consider is usernames vs full names. In the context of GitHub activity, most commits, issues, PRs, etc are all shown in terms of username. So for someone examining the contributors to a repo they are familiar with, seeing familiar usernames from their interactions might be more informative. Seeing the full name in the tooltip is still useful.

**Comment by aidan-epperly** [comment]
Thanks! PR #400 should fix all of these. Please let me know if there is anything else you notice that needs help. It is hard for me to test out the usability of my own work.

**Comment by LRWeber** [comment]
> It is also slightly awkward to have the tips for the lowest levels active in the upper levels; I could be trying to hover over the `hpcgroup` just to read the group name, but instead I keep seeing repo and user names unless I'm carefully aiming for the outer edge (which most people are unlikely to do).

I think we still have this problem, but that may be a more complex fix. The new changes are definitely an improvement!

**Comment by aidan-epperly** [comment]
I guess this comes more down to the fact that I don't really know how d3-tip works as unlike d3-simpleslider I wasn't the one who first used it. I will read the documentation and figure out how to fix it. How many layers down do you want visible at a time?

**Comment by aidan-epperly** [comment]
How does this look:
![image](https://user-images.githubusercontent.com/29114346/88737362-d0f89500-d0ed-11ea-8064-4024e2dec755.png)

**Comment by LRWeber** [comment]
Hmm that seems like a lot of info.

It could be simplified by combining the org and repo names (e.g. LLNL/axom_data).
That actually might be a good idea in general since it would simplify the problem of trying to hover over an org and getting a repo name instead; You would still get the organization info regardless of what the intended target was. It would also provide ready clarification in those cases where multiple organizations have the same repo names.

Honestly, I don't think we would need to see the user details until we're down at the user level.

**Comment by aidan-epperly** [comment]
Alright, I have the information displaying properly now except that it always displays above the node that is hovered over. So hovering over a user node in LLNL/lustre would show LLNL/lustre right over the user node.

**Comment by aidan-epperly** [comment]
Doesn't quite do the problem justice:
![image](https://user-images.githubusercontent.com/29114346/88825721-c2a58a00-d17c-11ea-8b1c-a5299dcdc0f1.png)

**Comment by aidan-epperly** [comment]
Legend for zoomable:
![image](https://user-images.githubusercontent.com/29114346/88864487-2b5f2780-d1ba-11ea-99e9-dc413a8d804b.png)

**Comment by aidan-epperly** [comment]
Zoomed in:
![image](https://user-images.githubusercontent.com/29114346/88864543-4d58aa00-d1ba-11ea-962a-20a33b3ff84b.png)

**Comment by aidan-epperly** [comment]
I think this is at least mostly finished for now, so I am going to close it.
