### ISSUE TITLE
Add some project logos?

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/llnl.github.io#405]
Awesome project!

Would it be possible to add some additional project logos? 

* Axom: https://github.com/LLNL/axom/blob/develop/share/axom/logo/axom_logo.png
* Raja: https://github.com/LLNL/RAJA/blob/develop/share/raja/logo/RAJA_LOGO_Color.png

I see some of the pieces, but I'm not sure how I'd test it and/or check that I didn't miss anything.

**Comment by IanLee1521** [comment]
Resolved by #406 -- Thanks @LRWeber !

**Comment by kennyweiss** [comment]
Thanks!
