### ISSUE TITLE
Edits to "Most Popular Repos" Page

### ISSUE THREAD

**Issue by aidan-epperly** [LLNL/llnl.github.io#407]
Continuation of discussion from #404

**Comment by LRWeber** [comment]
For reference: https://developer.github.com/v3/repos/statistics/#get-the-weekly-commit-activity
Data sample: https://api.github.com/repos/LLNL/llnl.github.io/stats/code_frequency

It might make sense to have a slider similar to the license graph that allows us to just swap between commits and line activity for the activity graphs.

**Comment by aidan-epperly** [comment]
> It might make sense to have a slider similar to the license graph that allows us to just swap between commits and line activity for the activity graphs.

I can do that reasonably easily, especially with d3 v5 joins.

**Comment by aidan-epperly** [comment]
Any work that we do here will also help with the "What's Hot" subpage as well, as figuring out a way of determining how much activity has occurred in a repo in the past ~1 month will be useful.

**Comment by IanLee1521** [comment]
This actually had me thinking... I wonder if we should split the data out of this repo and in to a separate repo (maybe like `github-data` that will help us not fill up this one and also give us the ability to re-do the repo if we need to... 

Then we can throw all the data in to it that we want, and just keep this repo as the frontend.

Thoughts?

**Comment by LRWeber** [comment]
That could be risky since it could be version dependent as we change what data we're getting etc. Wouldn't want to get them out of sync.

It would also completely change how the site has to fetch the data, since it isn't a part of the same GitHub pages site's internal files.

**Comment by IanLee1521** [comment]
That's fair. I was thinking that if we published it as a gh-pages site itself (auto-updating via the bot) then (since that's mainly how we do the data updates today) that we could reference it as `https://software.llnl.gov/github-data/.../thing.json`

**Comment by LRWeber** [comment]
That wouldn't be so bad.

It's mostly getting them out of sync that would concern me, since we can't exactly guarantee a simultaneous re-deployment. For example, I've just been renaming data files to accommodate both commit count and line change activity records....

**Comment by IanLee1521** [comment]
Hmm. yeah... I wonder if we can make one project trigger a update in the other.

**Comment by LRWeber** [comment]
Even if we could, the time between commit and successful site deployment is out of our hands. It's a pretty short window, but still.

**Comment by aidan-epperly** [comment]
Brief note on what Ian and I talked about in our meeting today:
![image](https://user-images.githubusercontent.com/29114346/89593390-dd72a100-d803-11ea-9756-e03f656747d7.png)
Any thoughts on this @IanLee1521 ?

**Comment by IanLee1521** [comment]
I'd probably put it at the top of the page since it applies to so much.

Might be worth also: 1) making links to the respective projects and 2) including the number of stars e.g. `#1 openzfs/zfs (5700)`

Also, this might just be me, but I feel twitchy about `#4` just hanging out on it's own.. maybe we could do two rows of 5? Or a pyramid:

1
2 3
4 5 6
7 8 9 10

?

**Comment by aidan-epperly** [comment]
Yes, I can do that. The problem is that when I do 2 columns, it looks un-centered even though it is. I will have to work on that then.

**Comment by aidan-epperly** [comment]
This is what it looks like with the list in 2 columns:
![image](https://user-images.githubusercontent.com/29114346/89662227-9f6b9080-d888-11ea-9719-80a552595999.png)

**Comment by aidan-epperly** [comment]
Here is it centered:
![image](https://user-images.githubusercontent.com/29114346/89666673-9fbb5a00-d88f-11ea-90d4-a3ed175e6e9a.png)

**Comment by IanLee1521** [comment]
How does it look as two rows of five, instead of two columns?

**Comment by aidan-epperly** [comment]
What it looks like:
![image](https://user-images.githubusercontent.com/29114346/89697110-89cd8980-d8cf-11ea-8571-c5cd98c85606.png)

**Comment by LRWeber** [comment]
I personally like that layout better, but the ordering isn't exactly intuitive. Could it instead be:
1 2 3 4 5
6 7 8 9 10

It might benefit from some additional spacing between the two lines that way as well.

**Comment by aidan-epperly** [comment]
Changed the layout:
![image](https://user-images.githubusercontent.com/29114346/89808283-c9be8780-daee-11ea-9284-e825837e520a.png)

**Comment by LRWeber** [comment]
> For reference: https://developer.github.com/v3/repos/statistics/#get-the-weekly-commit-activity
> Data sample: https://api.github.com/repos/LLNL/llnl.github.io/stats/code_frequency
> 
> It might make sense to have a slider similar to the license graph that allows us to just swap between commits and line activity for the activity graphs.

Our data now includes activity in the form of line additions and deletions! ([`explore/github-data/labRepos_ActivityLines.json`](https://github.com/LLNL/llnl.github.io/blob/13275a87bbc5c479f358a55379fd751bf8c5e8e7/explore/github-data/labRepos_ActivityLines.json))

**Comment by aidan-epperly** [comment]
> > For reference: https://developer.github.com/v3/repos/statistics/#get-the-weekly-commit-activity
> > Data sample: https://api.github.com/repos/LLNL/llnl.github.io/stats/code_frequency
> > It might make sense to have a slider similar to the license graph that allows us to just swap between commits and line activity for the activity graphs.
> 
> Our data now includes activity in the form of line additions and deletions! ([`explore/github-data/labRepos_ActivityLines.json`](https://github.com/LLNL/llnl.github.io/blob/13275a87bbc5c479f358a55379fd751bf8c5e8e7/explore/github-data/labRepos_ActivityLines.json))

Great! One question before I add this. I can think of three different ways to use additions/deletions to determine activity:

1. |additions| + |deletions|
2. |additions| - |deletions|
3. |additions|

Which do you think is the best?

**Comment by LRWeber** [comment]
Hmmm I would think probably just additions.
An edit to a line counts as 1 addition and 1 deletion, so counting it twice doesn't really make sense, but neither does cancelling itself out.

**Comment by aidan-epperly** [comment]
My plan right now is to try to have one slider that would update the whole page. Does that sound good?

**Comment by aidan-epperly** [comment]
I know that it says by stars, but this is most popular by line additions:
![image](https://user-images.githubusercontent.com/29114346/89836530-d1485580-db1b-11ea-8321-f5fff82053e8.png)

And here is the commit breakdown of those ten:
![image](https://user-images.githubusercontent.com/29114346/89836610-02c12100-db1c-11ea-9524-957e8029bf0b.png)

**Comment by LRWeber** [comment]
It'll probably look much nicer once that massive change in `PRUNERS/llvm-project` behavior falls off the timeline. 😅

**Comment by aidan-epperly** [comment]
I was also considering narrowing the time frame used to determine popularity which would remove it as it has not been active in some time.

**Comment by aidan-epperly** [comment]
Dynamic text sizing to prevent overlap:
![image](https://user-images.githubusercontent.com/29114346/89841749-a1ec1580-db28-11ea-9d89-52302d0cae07.png)

**Comment by LRWeber** [comment]
> I was also considering narrowing the time frame used to determine popularity which would remove it as it has not been active in some time.

That particular repo is an odd situation and is actually a fork of another one of our projects.... We've looked into it previously. https://github.com/LLNL/llnl.github.io/pull/295#issuecomment-543417414

A narrower time frame for popularity might make sense. Or possibly an adjustable time frame (with 1 year as the max), although that would be more complicated.

**Comment by aidan-epperly** [comment]
I am realizing now that I let my work on the new page and this one get kind of intertwined, so a lot of the work that I have done here really should not be used here and instead should be used for #411 . Makes no sense to base popularity off of additions 😅

**Comment by aidan-epperly** [comment]
@LRWeber Is there any way to make the file only save the last year of commits? It takes about a minute just to run the reformat data method on the file which is ~850,000 lines

**Comment by aidan-epperly** [comment]
![image](https://user-images.githubusercontent.com/29114346/89929450-1329d800-dbbe-11ea-86b8-1bd7516c41f8.png)

**Comment by aidan-epperly** [comment]
![image](https://user-images.githubusercontent.com/29114346/89930921-54bb8280-dbc0-11ea-848f-e3a35a837b62.png)

**Comment by aidan-epperly** [comment]
Most likely the final version:
![image](https://user-images.githubusercontent.com/29114346/89932393-6b62d900-dbc2-11ea-89cf-075eeabaac81.png)

**Comment by LRWeber** [comment]
> @LRWeber Is there any way to make the file only save the last year of additions? It takes about a minute just to run the reformat data method on the file which is ~850,000 lines

Yikes! Based on the other history data, I had thought that was what it did already, but apparently not! I'll see what I can do.

**Comment by aidan-epperly** [comment]
> Yikes! Based on the other history data, I had thought that was what it did already, but apparently not! I'll see what I can do.

I filtered it to only look at the top ten repos earlier and that fixed the time problem, but it is still a bit large.

**Comment by LRWeber** [comment]
> > Yikes! Based on the other history data, I had thought that was what it did already, but apparently not! I'll see what I can do.
> 
> I filtered it to only look at the top ten repos earlier and that fixed the time problem, but it is still a bit large.

Fixed with #414 !
The data hasn't been changed yet; I wasn't sure if I should take credit for the nearly 800k lines of code it changed!

**Comment by aidan-epperly** [comment]
Here is the graph and slider:
![image](https://user-images.githubusercontent.com/29114346/89955391-c78c2400-dbe7-11ea-9f49-c052e7ff660e.png)

**Comment by aidan-epperly** [comment]
I was kinda just curious about this:
![image](https://user-images.githubusercontent.com/29114346/90075538-814fc700-dcb2-11ea-830f-05b42851d446.png)
But then I felt like it would make a good addition. Planning to make a version for line additions, or possibly just have it update with the slider?

**Comment by aidan-epperly** [comment]
How's this:
![image](https://user-images.githubusercontent.com/29114346/90156399-3e890000-dd41-11ea-842e-5d854fe09820.png)

**Comment by tzanio** [comment]
Could the 68M lines *added* really be right (or maybe it is added + deleted)?! That's just mind-boggling.

**Comment by aidan-epperly** [comment]
For context, last week, llnl.github.io had over a million lines added and has had a minimum of 7000 lines a week for the last year

**Comment by LRWeber** [comment]
> Could the 68M lines _added_ really be right (or maybe it is added + deleted)?! That's just mind-boggling.

It may also be worth noting that a line added doesn't necessarily mean a brand new line; An edited line counts as one addition and one deletion.

**Comment by aidan-epperly** [comment]
> I wonder if it makes sense to include the the top N separately in the pie. E.g. rather than just the "top 10" or "not top 10" have "# 1", "# 2", ..., "# 10", "non top 10"

I worry that, as in the case of the line additions where the top ten already only make up 2%, that separating into even smaller subsections would make each slice too small to be of note.

**Comment by IanLee1521** [comment]
oh, hmm... I think I meant "top 10 by number changes" (or 5 if it makes more sense). Might not be the same 10 as the "top 10 by stars"

**Comment by aidan-epperly** [comment]
I thought about doing something along these lines, but I found that the most popular repos by lines were mostly data repos. I am doing something similar also with the "What's Hot" which deals with this kind of popularity, though I do weight by commits mainly to avoid data repos which have low commit counts with high lines added.

**Comment by IanLee1521** [comment]
Hmm, yeah... Just trying to think of ways to have more than simply "in" vs "out" circle charts...

Maybe group by org? I'm not sure... maybe not useful

**Comment by aidan-epperly** [comment]
> Hmm, yeah... Just trying to think of ways to have more than simply "in" vs "out" circle charts...
> 
> Maybe group by org? I'm not sure... maybe not useful

Maybe I could add a similar animation to the pie charts as is in the sunburst to allow you to click on them to get a breakdown just among the top 10?
