### ISSUE TITLE
"What's Hot" Page

### ISSUE THREAD

**Issue by aidan-epperly** [LLNL/llnl.github.io#411]
This issue will track the creation of the new, "What's Hot" or "Trending Repos" page.

**Comment by aidan-epperly** [comment]
First graph of popular repos:
![image](https://user-images.githubusercontent.com/29114346/89696130-52f57480-d8cb-11ea-859c-ee1e2071e49c.png)

**Comment by aidan-epperly** [comment]
The fact that the most recent weeks are so high compared to the rest of the graph gives me hope that this is, in fact, a good method of determining relative activity.

**Comment by aidan-epperly** [comment]
Removing most popular repos:
![image](https://user-images.githubusercontent.com/29114346/89818859-52ddba80-daff-11ea-87df-59cac4f5748e.png)

**Comment by aidan-epperly** [comment]
![image](https://user-images.githubusercontent.com/29114346/89819388-32fac680-db00-11ea-92d4-7e6bfa652352.png)

**Comment by hauten** [comment]
this seems done, per https://github.com/LLNL/llnl.github.io/issues/407, so i'm closing it
