### ISSUE TITLE
Remove forks of things in our orgs from vis

### ISSUE THREAD

**Issue by IanLee1521** [LLNL/llnl.github.io#415]
Noticed that we have forks of our own projects in other orgs. 

E.g. https://github.com/visit-dav/spack and https://github.com/rose-compiler/spack are forks of https://github.com/spack/spack , all three are LLNL operated.

Maybe we can filter out the forks if we have the "parent" in the LLNL orgs already? (need the `"parent": "full_name"` from https://api.github.com/repos/visit-dav/spack)

**Comment by LRWeber** [comment]
Duplicate of #300 ?

**Comment by IanLee1521** [comment]
Yeah, it really kind of is... I will close this and move my comment to that one.

This had a more specific action, and was maybe a bit more tightly focused than that one.
