### ISSUE TITLE
Better usability of filtered News page

### ISSUE THREAD

**Issue by hauten** [LLNL/llnl.github.io#446]
Follow-up from issue #441 and PR #445. News shows the 20 most recent posts. The filters show a subset of the non-filtered 20. With the new category filters activated, it can be jarring/confusing to see only a couple of posts. The page needs to (1) better communicate that the full archive of news is available on the Archive page and/or (2) what you get on the News page, filtered or not, is a subset of the Archive. The button at the bottom that leads to the Archive may need to be moved or replaced with something else. The ultimate solution may be to revise the "20 posts" rule such that any active filter shows 20 of that type of post.

**Comment by LRWeber** [comment]
Solved by #447
