### ISSUE TITLE
Filtering of dependency graph

### ISSUE THREAD

**Issue by aidan-epperly** [LLNL/llnl.github.io#449]
The dependency graph can often be difficult or impossible to navigate, so I am adding some filtering options and a search bar.

**Comment by aidan-epperly** [comment]
Color by language:
![image](https://user-images.githubusercontent.com/29114346/92961862-de12de80-f424-11ea-8d09-e8c91cca0057.png)

**Comment by aidan-epperly** [comment]
![image](https://user-images.githubusercontent.com/29114346/93117350-8e762200-f673-11ea-9c37-31865cc3ad46.png)

**Comment by aidan-epperly** [comment]
![image](https://user-images.githubusercontent.com/29114346/93144642-5258b680-f69f-11ea-9c91-1b81d815d733.png)

**Comment by IanLee1521** [comment]
What does the "Code by Language" in the bottom right mean? Is that meant to just be a description of what is shown? Or is that a selector of some kind?

Are the colors pinned? E.g. will Python always be that blue color?

**Comment by LRWeber** [comment]
> Are the colors pinned? E.g. will Python always be that blue color?

Those particular colors are. They are based on GitHub's colors used for the Language breakdowns they display on repos' GitHub pages.
![image](https://user-images.githubusercontent.com/29315109/93235778-dc059400-f732-11ea-8637-5f59b6009982.png)

**Comment by aidan-epperly** [comment]
Yes, though I added a color for CMake.

**Comment by hauten** [comment]
this seems done, so i'm closing it
