### ISSUE TITLE
Odd behavior on popular repo activity graph

### ISSUE THREAD

**Issue by aidan-epperly** [LLNL/llnl.github.io#489]
Noticed some odd behavior on this graph:
![image](https://user-images.githubusercontent.com/29114346/105780618-b892f700-5f25-11eb-95b0-a8dc84e1845e.png)

**Comment by LRWeber** [comment]
Hmm, the "Show Activity by Line Additions" view look fine, but "Show Activity by Commits" is definitely broken.
 The JSON data is there, so I don't think it's just a bug in today's data collection....

**Comment by aidan-epperly** [comment]
May be a 2021 problem.
