### ISSUE TITLE
Dependency issues when used with Ruby 3.0.0

### ISSUE THREAD

**Issue by JustinGOSSES** [LLNL/llnl.github.io#498]
These are a few additional dependency installation steps I had to follow using Ruby 3.0.0 and MacOS.
1. Ruby 3.0 no longer comes with webrick as described [here](https://github.com/github/pages-gem/issues/752).
`bundle add webrick`
2. eventmachine doesn't compile correctly on MacOS for Ruby 3.0.0 due to how MacOS in 10.15 handles openssl as described [here](https://github.com/eventmachine/eventmachine/issues/932). so I had to run `gem install eventmachine -- --with-openssl-dir=/usr/local/opt/openssl@1.1`

**Comment by IanLee1521** [comment]
Good catch.

I recall running in to something similar on another jekyll project recently.

If you're willing to submit a pull request to make the changes to address that, we'd be grateful!

**Comment by JustinGOSSES** [comment]
Added it to tip section of README instead of actual dependencies as it is probably better to advise people to use the version of Ruby used by Github Pages rather than try to get a dependency set up that works for all versions of Ruby.
