### ISSUE TITLE
Small add to documentation on in _explore folder

### ISSUE THREAD

**Issue by JustinGOSSES** [LLNL/llnl.github.io#499]
Only step not noted in https://github.com/LLNL/llnl.github.io/tree/main/_explore was that there is a requirements.txt file in the scripts folder and to run the scripts, you need to install those dependencies. 

A small thing to leave out as most people can figure it out, but probably good to include for completeness.

**Comment by IanLee1521** [comment]
Note that there is also more complete information like what I think you're looking for in the `scripts/` sub directory: https://github.com/LLNL/llnl.github.io/tree/main/_explore/scripts
