### ISSUE TITLE
Strange viewport display on mobile and tablet

### ISSUE THREAD

**Issue by IanLee1521** [LLNL/llnl.github.io#5]
Doesn't have any issues in the Chrome dev tools, but the main page (software.llnl.gov) doesn't fit properly in the viewport on iPhone / iPad devices. Tested with Safari and Chrome.

**Comment by tzanio** [comment]
Not sure if it's connected, but the left margin in the News page is also bad on iPhone.

**Comment by IanLee1521** [comment]
Appears to be fixed with recent CSS updates (161176e) @tzanio, could you confirm on your end?

**Comment by tzanio** [comment]
Yep, it looks good now.
