### ISSUE TITLE
get_repos_starhistory.py has this error: AttributeError: type object 'datetime.date' has no attribute 'fromisoformat'

### ISSUE THREAD

**Issue by JustinGOSSES** [LLNL/llnl.github.io#503]
This error appeared upon completion of running MASTER.sh:

```
Traceback (most recent call last):
  File "get_repos_starhistory.py", line 64, in <module>
    map(toDate, dataCollector.data["data"][repo]["stargazers"]["edges"])
  File "get_repos_starhistory.py", line 59, in toDate
    return next_weekday(date.fromisoformat(isoStr["starredAt"].split("T")[0]), 0)
AttributeError: type object 'datetime.date' has no attribute 'fromisoformat'
FAILED - get_repos_starhistory.py
```
Initially, it looked like the process still completed, so I didn't worry about it much, but it actually seems to prevent any new star and dependency data from being written.

Running on MacOS 10.13.6. 

I didn't get this error on a different computer last week. I was also pointing the script at different repositories. There's nothing in the error message that tells me a specific repository the error might have occurred on.

**Comment by LRWeber** [comment]
@JustinGOSSES Can you check what is written at the end of the `_explore/LAST_MASTER_UPDATE.log` file that should have been generated? That should give us some insight into what repository it was working on.

**Comment by JustinGOSSES** [comment]
The end of the log file says


```
'simpeg/website'
Using cached query 'repo-Stargazers.gql'
Page 1
Sending GraphQL query...
Checking response...
HTTP STATUS 200 OK
API Status {"reset": 1618596046, "limit": 5000, "remaining": 3023}
Data received!
'simpeg/website' Done!

Collective data gathering complete!
Traceback (most recent call last):
  File "get_repos_starhistory.py", line 64, in <module>
    map(toDate, dataCollector.data["data"][repo]["stargazers"]["edges"])
  File "get_repos_starhistory.py", line 59, in toDate
    return next_weekday(date.fromisoformat(isoStr["starredAt"].split("T")[0]), 0)
AttributeError: type object 'datetime.date' has no attribute 'fromisoformat'
FAILED - get_repos_starhistory.py
```

**Comment by LRWeber** [comment]
@JustinGOSSES What version of Python are you using?
I believe `fromisoformat` was added in Python 3.7. The previous computer you used most likely had a newer version of Python than the one you are currently using.

**Comment by JustinGOSSES** [comment]
Ah, that's almost certainly it. I'll try it again and report back.

**Comment by IanLee1521** [comment]
If that ends up being the case (I agree, I think Python version is the issue) then maybe we should try to catch that exeption and emit a warning on "python < 3.7" ?

**Comment by LRWeber** [comment]
> If that ends up being the case (I agree, I think Python version is the issue) then maybe we should try to catch that exeption and emit a warning on "python < 3.7" ?

Good idea! I'll add that to the script.

**Comment by JustinGOSSES** [comment]
Yes, accidentally used python 3.5 instead of 3.7. 

Once I changed that,I no longer had that problem.

**Comment by IanLee1521** [comment]
Glad to hear it.

now with the change @LRWeber made in https://github.com/LLNL/llnl.github.io/pull/504 it will hopefully be a little clearer about that requirement.
