### ISSUE TITLE
Better description of per-project icons/data on catalog page

### ISSUE THREAD

**Issue by neely4** [LLNL/llnl.github.io#51]
The main catalog page has 3 (sometimes 4) icons under each project with an integral value (or sometimes nothing) next to it. To a newbie, it's not obvious what those refer to - at least without a fair bit of clicking through to the github site.

Maybe a simple legend at the top would suffice. Or a mouseover action on each that describes what it represents?

**Comment by LRWeber** [comment]
I've tried doing this with `alt` and/or `title` attributes on the links, but it doesn't seem to show up at all...

**Comment by IanLee1521** [comment]
How does that look for you now @neely4  ?
