### ISSUE TITLE
Suggestion for organization of site

### ISSUE THREAD

**Issue by vsoch** [LLNL/llnl.github.io#513]
I took some notes this weekend about the current site, and I have a few suggestions for improvement!

When I come to the site, I put myself in the mindset of a visitor who is not familiar with the lab or the software developed within. If I'm a developer, I'm very interested in "What software is here that I might be interested in?" The front page is good in that I can quickly click on a topic of interest and I'm taken to the search view, and the names of the libraries and stars quickly show me "Wow there are a lot of stars on this package!"

So let's say I follow a package to the search view, and I click on the package. I see a page like this:

https://software.llnl.gov/repo/#/hypre-space/hypre

These visualizations are cool, but if I'm asking the question "What does this library do, and do I have a matching use case?" I'm not super interested in the number of contributors, frequency of contribution, or stars. This might be a section or tab for metrics, but the main content of interest would really be "These are the problems this software can solve, this is how it can help you" and then here is the project homepage for more detail. This is harder to implement because work needs to be done to collect this information for each package, but I think the package-specific pages would be more useful.

My other suggestion is about the links at the top. When I came to the site for the very first time, my expectation of clicking "Explore" would be to take me to that search interface. I was surprised to see a bunch of plots, which, although cool, isn't really what I'd first be looking for. So perhaps the explore link should go to search, and the (current) explore page should be more properly labeled as some kind of metrics or visualization?

Finally, if I'm someone not at the lab, the RADIUSS term means nothing to me, and I would have to mouse it over to see what is there. I'm wondering if (at least the link) can be more generalized so no special knowledge is needed to browse the site.

**Comment by IanLee1521** [comment]
Thanks @vsoch these suggestions sound pretty good to me.

Do you happen to have the time / willingness to work on these? Pull requests are very welcome. I can even provide a P/T to fund your time working on them if you need that. Hit me up in Mattermost if you need to discuss more.

**Comment by vsoch** [comment]
Nah I doubt I need funding I can just do it :) RADIUSS would cover it no?

**Comment by vsoch** [comment]
See #514

**Comment by hauten** [comment]
Closed via https://github.com/LLNL/llnl.github.io/pull/514
