### ISSUE TITLE
CDN image links are broken again

### ISSUE THREAD

**Issue by hauten** [LLNL/llnl.github.io#518]
Our Site Improve crawler flagged 5 broken links, all of which are cdn.llnl.gov. It's the four footer logos plus onelab.css in the header. Prod, w/o VPN:

![image](https://user-images.githubusercontent.com/31740953/121918088-92120480-ccea-11eb-924b-c89ba3865bf4.png)
![image](https://user-images.githubusercontent.com/31740953/121918308-ca194780-ccea-11eb-9688-c811735303f6.png)

**Comment by LRWeber** [comment]
We could potentially replace the links in `_includes/head.html`.
Unfortunately, even if we did that, a number of these issues would still exist due to our use of the remote Jekyll theme for LLNL.
https://github.com/LLNL/llnl.github.io/blob/773b6d7694918cc4734e2fe21c7e4cbf9f1304a4/_config.yml#L5
