### ISSUE TITLE
need navigation to Using GitHub sub-page

### ISSUE THREAD

**Issue by hauten** [LLNL/llnl.github.io#57]
https://software.llnl.gov/about/using-github/
This page is not accessible from /about (or anywhere else in the nav).

Some options:
Add to top menu when mousing over About. (But none of the other menu options has a sub-page like this, so enh...?)
Add a link on the About page, for instance: "Read more about using GitHub." and link the sentence or the last two words to the sub-page. I would put this sentence above the Contact heading.

**Comment by IanLee1521** [comment]
@gonsie -- this is the issue I was mentioning to you today, if you have time to take a look (or need a break from all your reading ;) )

**Comment by gonsie** [comment]
For tracking purposes, I think these are the pages that are missing:
- `about/open-source.md` 
- `about/using-github.md`
- `about/contributing.md`
- `about/licenses/index.md`

Let me know if there are others. I'll start by adding some links directly on the About page.

**Comment by gonsie** [comment]
Here is a code snippet that could be used to automatically find each `about` subpage: 

```liquid
<ul>
{% for p in site.pages %}
{% if p.url contains "about" and p.url != "/about/" %}
<li>{{ p.title }} - {{ p.url }}</li>
{% endif %}
{% endfor %}
</ul>
```

That said, I'm leaning to hand-coding the additional pages into the navigation. This makes it easy to choose a short name for the navigation.

**Comment by hauten** [comment]
Looks great, thank you

**Comment by IanLee1521** [comment]
I'm going to go ahead and re-open until we have a real navbar added.
