### ISSUE TITLE
Combine data update with repo update

### ISSUE THREAD

**Issue by IanLee1521** [LLNL/llnl.github.io#82]
@LRWeber  -- We should consider adding a `make update` Makefile target to this repo which combines the `./MASTER.sh` process with updating the Git repo itself.

This was prompted by my stumbling upon https://github.com/GSA/data/blob/master/enterprise-architecture/update.sh by @afeld

**Comment by LRWeber** [comment]
This issue is addressed alongside the automatic updates via GitHub Actions. Automatic update issues are covered in #43
