### ISSUE TITLE
Integrate Star Graphs into Explore Page

### ISSUE THREAD

**Issue by IanLee1521** [LLNL/llnl.github.io#84]
I just learned about https://github.com/timqian/star-history from @behlendorf and think that it would be an interesting feature to add to our exploration page.

Example, with our top 9 projects:

http://www.timqian.com/star-history/#zfsonlinux/zfs&spack/spack&zfsonlinux/zfs-auto-snapshot&zfsonlinux/spl&zfsonlinux/pkg-zfs&mfem/mfem&rose-compiler/rose&hpc/dcp&chaos/pdsh

cc/ @LRWeber + @dinatale2 in case you're interested in working on this one.

**Comment by hauten** [comment]
@aidan-epperly Is this issue/idea obsolete thanks to the upgrades you've made to Explore?

**Comment by aidan-epperly** [comment]
We don't have anything that graphs stars/time, but I would say that it isn't strictly needed? It would fit in the most popular repos page. If we wanted to add a third graph.

**Comment by IanLee1521** [comment]
code for that graph of theirs (?): https://github.com/timqian/star-history/blob/master/core/getStarHistory.js

**Comment by IanLee1521** [comment]
Honestly, I really like the idea of a stars over time graph if we could get it in to the site... 

Maybe with a double ended selector for dynamically changing the min / max stars to show on the graph?

**Comment by aidan-epperly** [comment]
Here is what the star history graph looks like as of now:
![image](https://user-images.githubusercontent.com/29114346/90700402-a0ae9d00-e23a-11ea-889e-ef898789776b.png)

**Comment by tzanio** [comment]
This will be really cool to have, both globally and on repository level!

**Comment by aidan-epperly** [comment]
Yes! I think it will. Right now the biggest problem is:
![image](https://user-images.githubusercontent.com/29114346/90701024-2f6fe980-e23c-11ea-971e-0df0034e5b52.png)

**Comment by LRWeber** [comment]
> Yes! I think it will. Right now the biggest problem is:
> ![image](https://user-images.githubusercontent.com/29114346/90701024-2f6fe980-e23c-11ea-971e-0df0034e5b52.png)

Check the graph styling for the Creation History graph; It had the same problem of super-dense data points, so we adopted a modified style for the dots!

**Comment by aidan-epperly** [comment]
This is also something that would be solved by having fewer data points, so if we choose to do that it might make dense points unnecessary.

**Comment by aidan-epperly** [comment]
Here is what the dense points look like:
![image](https://user-images.githubusercontent.com/29114346/90792079-df863680-e2be-11ea-9668-0acaa94f9f4a.png)

**Comment by aidan-epperly** [comment]
Ideally, what would the maximum number of entries per repo be?

**Comment by aidan-epperly** [comment]
Original:
![image](https://user-images.githubusercontent.com/29114346/90807526-74932a80-e2d3-11ea-8312-1d743fa9f3cd.png)
Compressed:
![image](https://user-images.githubusercontent.com/29114346/90807626-98ef0700-e2d3-11ea-8792-e2f111908d97.png)

**Comment by aidan-epperly** [comment]
Original spack:
![image](https://user-images.githubusercontent.com/29114346/90807719-c50a8800-e2d3-11ea-9877-2aeec6969f2a.png)
Compressed spack:
![image](https://user-images.githubusercontent.com/29114346/90807850-f1be9f80-e2d3-11ea-9232-a6d1536b4743.png)

**Comment by aidan-epperly** [comment]
It's about a third the number of points for spack and not much in the shape is lost. For small repos though it can change it a lot as you can see.

**Comment by aidan-epperly** [comment]
Compression on llnl.github.io with lower tolerance and higher power:
![image](https://user-images.githubusercontent.com/29114346/90809666-abb70b00-e2d6-11ea-8ec5-e0dcfa8a1834.png)

**Comment by aidan-epperly** [comment]
More points but preserves more info:
![image](https://user-images.githubusercontent.com/29114346/90812112-862c0080-e2da-11ea-8473-d0d75399681a.png)

**Comment by aidan-epperly** [comment]
I am running this at the graph level, but it approximately halves the number of points which would probably bring the json file down to 30k lines. What do you think @LRWeber ?

**Comment by LRWeber** [comment]
> I am running this at the graph level, but it approximately halves the number of points which would probably bring the json file down to 30k lines. What do you think @LRWeber ?

How are you currently compressing that info?

**Comment by aidan-epperly** [comment]
Code:
``` js
    function deviationMetric(dateArray, valueArray, power) {
        const linearApproximation = d3.scaleLinear()
            .domain([dateArray[0], dateArray[dateArray.length - 1]])
            .range([valueArray[0], valueArray[valueArray.length - 1]]);

        let deviation = 0;
        
        for (var i = 0; i < dateArray.length; i++) {
            deviation += Math.pow(Math.abs(valueArray[i] - linearApproximation(dateArray[i])), power);
        }

        return deviation;
    }
```

``` js
    function compressRecursive(obj, tolerance = 2, power = 2) {
        const deviation = deviationMetric(obj.map(d => d.date), obj.map(d => d.value), power);
        
        if(deviation < tolerance) {
            return obj;
        } else {
            return compressRecursive(obj.slice(0, Math.floor(obj.length / 2) + 1)).concat([null].concat(compressRecursive(obj.slice(Math.floor(obj.length / 2)))));
        }
    }
```

**Comment by aidan-epperly** [comment]
Good medium size repo (RAJA) in terms of stars:
![image](https://user-images.githubusercontent.com/29114346/90824738-bb414e80-e2ec-11ea-8a7a-0aabe5bfe6ba.png)

**Comment by LRWeber** [comment]
My concern is more about the amount of data we're trying to store than the number of points on the graph.
I personally don't have a problem with the high density, so long as it doesn't negatively impact page performance (which, as we saw for the activity graph, loading a large data file can do).

For similar reasons, compressing the data itself is likely more efficient than compressing the graph displayed to the user; It's the difference between running the more involved calculations once when the data is being collected (with nobody waiting for it in real time), or once for every time the page is visited (with the active user stuck waiting).

**Comment by aidan-epperly** [comment]
I was planning to do this on the data, but I first wanted to see what it would look like.

**Comment by LRWeber** [comment]
That's fair. I think, however, for compressing the data itself, a time-frame based compression method (which would give us a predictable max number of data points) may be preferable.

These graphs do help indicate reasonable ways of doing that; From the samples you've shown, it looks like even just having a single data point every couple of months still provides decent data resolution for several-year-old repos!

I like the idea we discussed previously, where the data point frequency would decrease the further back in time you go. This would help maintain a similar visual data resolution whether a project is 2 weeks old or 2 decades old!

**Comment by aidan-epperly** [comment]
Alright, I can implement that then. The one thing that we would lose is those large spikes in stars.

**Comment by LRWeber** [comment]
> Alright, I can implement that then. The one thing that we would lose is those large spikes in stars.

At the graph scale we're getting for those sample repos' timeframes, we should still see those visual spikes with a monthly count.
And if we have a higher frequency for the most recent dates, projects can still see if their recent activities have caused a spike!

**Comment by aidan-epperly** [comment]
Graph of all repos:
![image](https://user-images.githubusercontent.com/29114346/91083491-3e211c80-e5ff-11ea-8903-779e06c8af9b.png)

**Comment by aidan-epperly** [comment]
Graph with slider:
![image](https://user-images.githubusercontent.com/29114346/91097730-189f0d80-e615-11ea-8799-b48a08db61e3.png)
![image](https://user-images.githubusercontent.com/29114346/91097766-25bbfc80-e615-11ea-9206-3ef79fd99878.png)

**Comment by aidan-epperly** [comment]
Adjustable axis:
![image](https://user-images.githubusercontent.com/29114346/91200856-91a17200-e6b4-11ea-9d8a-0854abe4baf0.png)
