### ISSUE TITLE
Transition to remote theme

### ISSUE THREAD

**Issue by gonsie** [LLNL/llnl.github.io#88]
Transition this to the remote theme [Jekyll-LLNL-Theme](https://github.com/LLNL/Jekyll-LLNL-Theme). 

Be wary with the menu, the About page is from `about/index.md` and there are several subpages in that folder.

**Comment by IanLee1521** [comment]
See also dev.llnl.gov (internal) which just migrated to the remote theme successully.

**Comment by IanLee1521** [comment]
Completed with #164
