### ISSUE TITLE
Create listing of conferences / presentations being attended

### ISSUE THREAD

**Issue by IanLee1521** [LLNL/llnl.github.io#97]
* SciPy
* JupyterCon
* [PyCon](https://us.pycon.org)
* [DjangoCon](https://2018.djangocon.us)
* JuliaCon -- (Seth Bromberger)
* [DockerCon](https://2018.dockercon.com)
* [Supercomputing](https://sc18.supercomputing.org)
* [GitHub Universe](https://githubuniverse.com)

Continue to flesh out, cc/ @tgamblin

**Comment by tgamblin** [comment]
* ISC
* HPC User Meeting
* HPC Knowledge Meeting
* NCSA Industry partnership meeting.

**Comment by hauten** [comment]
Is this a list of comp/hpc events LLNL people go to regardless of whether open source related, or a narrower scope? I can likely add to it.

**Comment by IanLee1521** [comment]
I think we might want to scope it a couple of ways... Maybe we can have it be anything public and software related. Maybe we have a call out for "open source" but I suspect a lot of the things will be (or could be) categorized that way...

**Comment by IanLee1521** [comment]
* RedHat / Intel OpenFirst - https://www.redhat.com/en/events/open-first-washington-dc-september18

**Comment by tonyhutter** [comment]
- [ZFS User Conference](https://zfs.datto.com/)
- [OpenZFS Developers Summit](http://open-zfs.org/wiki/OpenZFS_Developer_Summit)

**Comment by IanLee1521** [comment]
DevOps
- [DevOps Summit](https://events.itrevolution.com)

**Comment by tgamblin** [comment]
* [PyBay](https://pybay.com/)
* [PEARC](https://www.pearc.org/) - maybe a good recruiting venue for admins (lots of university HPC folks attend)

These are some of the major research paper venues (in addition to SC):
* [IEEE Cluster](https://clustercomp.org/)
* [IPDPS](http://www.ipdps.org/)
* [ICS](https://www.ics-conference.org/)
* [PPoPP](https://ppopp19.sigplan.org/)
* [PLDI](https://pldi19.sigplan.org/)
* [ASPLOS](https://asplos-conference.org/)

**Comment by specialbrew** [comment]
[KubeCon / CloudNativeCon](https://events19.linuxfoundation.org/events/kubecon-cloudnativecon-north-america-2019/) - part the Linux Foundation

**Comment by hauten** [comment]
@IanLee1521, reviving this because we have a list & I may work on it during the next hackathon. We should talk about where to put this info & how you want it to look. One example is a basic list that gets updated every so often like https://data-science.llnl.gov/latest.

**Comment by IanLee1521** [comment]
@hauten that sounds great. Honestly, I'm happy to let you run with whatever proposal you like. 

One thing I do want to make sure we include though on our list, that isn't on the DSI one is a highlight of anyone that we have presenting at a conference.

**Comment by tgamblin** [comment]
[FOSDEM](https://fosdem.org/)

**Comment by hauten** [comment]
Note to self for when I deal with this at the next hackathon:
- [ ] Add page under News called Events.
- [ ] Leverage tags on posts so the Events page is filtered to show only the `event` tagged posts.
- [ ] Review existing posts with `event` tag to see if they are truly relevant (worst case: come up with a different tag for one or the other type of event). For example, 2018-10-27-sc18.md; some might need to be retagged like 2019-04-23-spackriken.md (which is really more of a trip report, not a preview of upcoming event).
- [ ] Establish template for `event` posts (related to issue #314).

Also, perhaps long term: Decide whether it's worth filtering OUT `event` posts from News & Archive. See also issue #252 which would be the ideal filtering of all News according to tag, and then it wouldn't matter if everything was mingled together.

**Comment by hauten** [comment]
OK, we now have an Events page (https://software.llnl.gov/news/events/) that filters *the news we know about*. Still to do would be to add attendee/presenter names to the template somewhere. The *real* (offline) effort is to find out who is planning to attend all of the events named above so a news post can be created.

**Comment by hauten** [comment]
Update 12/1/2020: No longer a dedicated Events page; now we have filterable news (& news archive) with `event` and `event-report` filters: https://software.llnl.gov/news/. @IanLee1521 Do you have any thoughts on this issue now?

**Comment by IanLee1521** [comment]
I think we can go ahead and close this now.

Though it's making me wonder if we need to have an "`upcoming`" label to filter on? (once we actually have upcoming things..

Use case being when we are going to be sending people to conferences and want to share that... maybe that's not a great thing for the website though...

**Comment by hauten** [comment]
In practice, I've been using `event` on a post when it's upcoming, then updating the post `event-report` when the event is over and there's video/slides/etc to link to. Totally open to doing it another way, however. We could use `upcoming-event` instead of `event` for instance?
