### ISSUE TITLE
Data mismatch?

### ISSUE THREAD

**Issue by IanLee1521** [LLNL/llnl.github.io#98]
It appears that the main page (https://software.llnl.gov) currently lists 457 projects, while the exploration page (https://software.llnl.gov/explore/) shows about 512 projects... 

Any idea what is going on here?

**Comment by LRWeber** [comment]
That's interesting.... When I visit those pages, both say 433.
Could there be something leftover in your browser cache?

**Comment by IanLee1521** [comment]
Huh... That's even stranger... Why did we have more projects than we currently have...? Maybe I need to re-run the data update and see what it comes up with today...

**Comment by IanLee1521** [comment]
Also, as a bit of an aside (maybe a separate ticket) we should try to get the data lists sorted somehow so that the changes from one update to the next are as minimal as possible... Is that something that you would be able to set up reasonably easily?

**Comment by LRWeber** [comment]
No need to re-run: there are fewer projects because there are literally fewer repos. It looks like a large number of LLNL organization repos have been deleted recently (LLNL/2018-ecp-exa-sim, LLNL/2019-incite-peac, LLNL/Aluminum, LLNL/Apollo, LLNL/CA, LLNL/CHiME, LLNL/CoMD, just to name the first handful I see).

The data is sorted already. There may have been more changes than usual due to the complete scripting change, which maybe have added/removed/reorganized a bit along with them. The data run before the last one I ran also seems to have ended up with a completely empty extRepos.json, which should not have been the case. My guess it that it encountered an error and never finished that script properly. A big part of the re-write includes better error case handling, so that shouldn't happen anymore.

**Comment by LRWeber** [comment]
As an added tip: the re-write added a wrapper to the MASTER script that generates a local log file (ignored by the repo). That makes it easy to run a quick post-update search for "Error" messages to catch anything that does go wrong. It's a good sanity check.

The only un-resolved error messages from my last run came from a couple repos that exist but are empty (LLNL/camp, LLNL/googletest-mpi-listener). Those are to be expected and get handled accordingly. All other errors came from arbitrary server-side API errors, but, with the new scripting, those queries all got retried and came back with proper responses.

**Comment by IanLee1521** [comment]
Looks like those that you listed as being "deleted" are now marked as private... I'll investigate what is going on there.

**Comment by LRWeber** [comment]
Ohhh interesting. The "private" status hides the repos from the API and treats them the same as a non-existent repo. (The same as trying to navigate to them in a browser.)

If you are able to see those repos as private, that would explain the strange data swings. I'm guessing you have a role within the LLNL GitHub org that lets you see them. I believe that if we have privileges to view a private repo, we should be able to generate a token that can see that information. So the data updates _you_ run will have additional repos included compared to what _I_ run.

This would also explain the data mismatch. Assuming that your role allows you to see the existence of these repos, but not all of their contents, there are certain data points that the API would be able to retrieve and others that they cannot. Depending on the data that feeds into a particular graph or list, the count would be different.

**Comment by IanLee1521** [comment]
Ahhh... So probably what we want to do is to update the scripts to limit the repos returned to only include the public repos. I know that is an option in the REST api, not sure what the process would be in the GraphQL api.

**Comment by LRWeber** [comment]
Our best bet is probably to review the actual access levels we give the specific token(s) we use when running the scripts. https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/#available-scopes

We may want to look into what it would take to turn the software.llnl.gov data collection into an actual OAuth App with its own authentication. I think that would give us a single, standard token we could run with.

**Comment by LRWeber** [comment]
I've managed to do the update run with a token with very minimal permissions:
read:org, read:user, user:email

@IanLee1521 Can you try generating (or modifying) a personal token with the same setup, and see if you get the same results?

**Comment by IanLee1521** [comment]
Hmm, it looks like I only have the "read:org" permission... I suspect it's because I am the org owner, so I see all the private repos...

I poked around in the docs to see if there was a way to limit the results to public only, but didn't see anything... Maybe @jbjonesjr can save us here?

**Comment by LRWeber** [comment]
Hmm. Maybe an OAuth App token would work independently of our individual permissions? It makes sense to have a single token for updates. If we want to set up an automatic system, we'll have to give it a token to use, and treating it as an application rather than using a personal token is probably better practice.

**Comment by jbjonesjr** [comment]
I think I saw something about this the other day!!

How are accessing the list of repositories?

/orgs/{org}/repos or something else?

Long story short, what i was reading about earlier in the week is a case where listing repos goes through what you `explicitly have access to` (org member for public repos, explicit access for private repos). If you org is set to give **EVERYONE** read access to private repos, that attribution doesn't necessarily flow to the API, hence the discrepancy. 

This may not be what's happening here, but curious if that seems plausible.

**Comment by LRWeber** [comment]
We're using the GraphQL API for that one. (See [this file](https://github.com/LLNL/llnl.github.io/blob/811640e49f788b659dc228ad8d295e309034d1b9/explore/queries/org-Repos-Info.gql).)

That's certainly why I'm not getting those private repos. Unfortunately, knowing that doesn't really give us a way to make sure Ian _doesn't_ get those repos. We'd be looking for a way to leave those repos out, not a way to make sure they're included.

Strange that the org public read settings don't quite carry through though.

**Comment by jbjonesjr** [comment]
ohhhhhh. gotcha. i read the part about discrepencies and thought that was the issue.

in your query, try changing
`repositories(first: $numRepos, after: $pgCursor) {`
to
`repositories(first: $numRepos, after: $pgCursor, privacy: PUBLIC) {`

**Comment by LRWeber** [comment]
Aha, that may be exactly what we're looking for! Thanks @jbjonesjr !

@IanLee1521 , I just updated the queries in the new "dataUpdate" branch. Can you try running an update from that branch, and see if you get the results we're looking for?

**Comment by IanLee1521** [comment]
Running the original now so I have something to compare..

As an FYI, I get:

```
> ./MASTER.sh
./MASTER.sh: line 3: syntax error near unexpected token `&'
./MASTER.sh: line 3: `unbuffer ./MASTER.sh.real |& tee -i ../github-data/LAST_MASTER_UPDATE.log'
```

So I'm running ``./MASTER.sh.real`` for now

**Comment by LRWeber** [comment]
Hmm, @IanLee1521 what shell are you using when you run the script? That may be one of those less cross-compatible commands.... Could be worth following up on it as a new issue.

Glad to hear that resolved the original issue though! I'll submit the pull request.

**Comment by IanLee1521** [comment]
I've tried with both zsh and bash, though the shebang line in the script should force it to bash...

Maybe it's a version issue?

```
$ zsh --version
zsh 5.5.1 (x86_64-apple-darwin17.5.0)
$ bash --version
GNU bash, version 4.4.23(1)-release (x86_64-apple-darwin17.7.0)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by LRWeber** [comment]
```
$ bash --version
GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
Yup, most likely a version issue. I'll look into possible modifications that are compatible with more current shells.
